/*
 * Assets - Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_npc_unit_v2_npc_units_id_or_class_name_get`]
#[derive(Clone, Debug)]
pub struct GetNpcUnitV2NpcUnitsIdOrClassNameGetParams {
    pub id_or_class_name: String,
    pub client_version: Option<String>
}

/// struct for passing parameters to the method [`get_npc_units_v2_npc_units_get`]
#[derive(Clone, Debug)]
pub struct GetNpcUnitsV2NpcUnitsGetParams {
    pub client_version: Option<models::models::DeadlockAssetsApiRoutesValidClientVersions>
}


/// struct for typed errors of method [`get_npc_unit_v2_npc_units_id_or_class_name_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetNpcUnitV2NpcUnitsIdOrClassNameGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_npc_units_v2_npc_units_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetNpcUnitsV2NpcUnitsGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}


pub async fn get_npc_unit_v2_npc_units_id_or_class_name_get(configuration: &configuration::Configuration, params: GetNpcUnitV2NpcUnitsIdOrClassNameGetParams) -> Result<models::NpcUnitV2, Error<GetNpcUnitV2NpcUnitsIdOrClassNameGetError>> {

    let uri_str = format!("{}/v2/npc-units/{id_or_class_name}", configuration.base_path, id_or_class_name=crate::apis::urlencode(params.id_or_class_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.client_version {
        req_builder = req_builder.query(&[("client_version", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NpcUnitV2`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NpcUnitV2`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetNpcUnitV2NpcUnitsIdOrClassNameGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_npc_units_v2_npc_units_get(configuration: &configuration::Configuration, params: GetNpcUnitsV2NpcUnitsGetParams) -> Result<Vec<models::NpcUnitV2>, Error<GetNpcUnitsV2NpcUnitsGetError>> {

    let uri_str = format!("{}/v2/npc-units", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.client_version {
        req_builder = req_builder.query(&[("client_version", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::NpcUnitV2&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::NpcUnitV2&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetNpcUnitsV2NpcUnitsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

