// <auto-generated>
/*
 * Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using DeadlockApiClient.Client;

namespace DeadlockApiClient.Model
{
    /// <summary>
    /// ActiveMatchPlayer
    /// </summary>
    public partial class ActiveMatchPlayer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActiveMatchPlayer" /> class.
        /// </summary>
        /// <param name="abandoned">abandoned</param>
        /// <param name="accountId">accountId</param>
        /// <param name="heroId">See more: &lt;https://assets.deadlock-api.com/v2/heroes&gt;</param>
        /// <param name="team">team</param>
        /// <param name="teamParsed">teamParsed</param>
        [JsonConstructor]
        public ActiveMatchPlayer(Option<bool?> abandoned = default, Option<int?> accountId = default, Option<int?> heroId = default, Option<int?> team = default, Option<ActiveMatchTeam?> teamParsed = default)
        {
            AbandonedOption = abandoned;
            AccountIdOption = accountId;
            HeroIdOption = heroId;
            TeamOption = team;
            TeamParsedOption = teamParsed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TeamParsed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ActiveMatchTeam?> TeamParsedOption { get; private set; }

        /// <summary>
        /// Gets or Sets TeamParsed
        /// </summary>
        [JsonPropertyName("team_parsed")]
        public ActiveMatchTeam? TeamParsed { get { return this.TeamParsedOption; } set { this.TeamParsedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Abandoned
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AbandonedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Abandoned
        /// </summary>
        [JsonPropertyName("abandoned")]
        public bool? Abandoned { get { return this.AbandonedOption; } set { this.AbandonedOption = new(value); } }

        /// <summary>
        /// Used to track the state of AccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> AccountIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [JsonPropertyName("account_id")]
        public int? AccountId { get { return this.AccountIdOption; } set { this.AccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of HeroId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> HeroIdOption { get; private set; }

        /// <summary>
        /// See more: &lt;https://assets.deadlock-api.com/v2/heroes&gt;
        /// </summary>
        /// <value>See more: &lt;https://assets.deadlock-api.com/v2/heroes&gt;</value>
        [JsonPropertyName("hero_id")]
        public int? HeroId { get { return this.HeroIdOption; } set { this.HeroIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Team
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TeamOption { get; private set; }

        /// <summary>
        /// Gets or Sets Team
        /// </summary>
        [JsonPropertyName("team")]
        public int? Team { get { return this.TeamOption; } set { this.TeamOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActiveMatchPlayer {\n");
            sb.Append("  Abandoned: ").Append(Abandoned).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  HeroId: ").Append(HeroId).Append("\n");
            sb.Append("  Team: ").Append(Team).Append("\n");
            sb.Append("  TeamParsed: ").Append(TeamParsed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AccountId (int) minimum
            if (this.AccountIdOption.IsSet && this.AccountIdOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for AccountId, must be a value greater than or equal to 0.", new [] { "AccountId" });
            }

            // HeroId (int) minimum
            if (this.HeroIdOption.IsSet && this.HeroIdOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for HeroId, must be a value greater than or equal to 0.", new [] { "HeroId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ActiveMatchPlayer" />
    /// </summary>
    public class ActiveMatchPlayerJsonConverter : JsonConverter<ActiveMatchPlayer>
    {
        /// <summary>
        /// Deserializes json to <see cref="ActiveMatchPlayer" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ActiveMatchPlayer Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> abandoned = default;
            Option<int?> accountId = default;
            Option<int?> heroId = default;
            Option<int?> team = default;
            Option<ActiveMatchTeam?> teamParsed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "abandoned":
                            abandoned = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "account_id":
                            accountId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "hero_id":
                            heroId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "team":
                            team = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "team_parsed":
                            string? teamParsedRawValue = utf8JsonReader.GetString();
                            if (teamParsedRawValue != null)
                                teamParsed = new Option<ActiveMatchTeam?>(ActiveMatchTeamValueConverter.FromStringOrDefault(teamParsedRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ActiveMatchPlayer(abandoned, accountId, heroId, team, teamParsed);
        }

        /// <summary>
        /// Serializes a <see cref="ActiveMatchPlayer" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="activeMatchPlayer"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ActiveMatchPlayer activeMatchPlayer, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, activeMatchPlayer, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ActiveMatchPlayer" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="activeMatchPlayer"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ActiveMatchPlayer activeMatchPlayer, JsonSerializerOptions jsonSerializerOptions)
        {
            if (activeMatchPlayer.AbandonedOption.IsSet)
                if (activeMatchPlayer.AbandonedOption.Value != null)
                    writer.WriteBoolean("abandoned", activeMatchPlayer.AbandonedOption.Value!.Value);
                else
                    writer.WriteNull("abandoned");

            if (activeMatchPlayer.AccountIdOption.IsSet)
                if (activeMatchPlayer.AccountIdOption.Value != null)
                    writer.WriteNumber("account_id", activeMatchPlayer.AccountIdOption.Value!.Value);
                else
                    writer.WriteNull("account_id");

            if (activeMatchPlayer.HeroIdOption.IsSet)
                if (activeMatchPlayer.HeroIdOption.Value != null)
                    writer.WriteNumber("hero_id", activeMatchPlayer.HeroIdOption.Value!.Value);
                else
                    writer.WriteNull("hero_id");

            if (activeMatchPlayer.TeamOption.IsSet)
                if (activeMatchPlayer.TeamOption.Value != null)
                    writer.WriteNumber("team", activeMatchPlayer.TeamOption.Value!.Value);
                else
                    writer.WriteNull("team");

            if (activeMatchPlayer.TeamParsedOption.IsSet)
                if (activeMatchPlayer.TeamParsedOption!.Value != null)
                {
                    var teamParsedRawValue = ActiveMatchTeamValueConverter.ToJsonValue(activeMatchPlayer.TeamParsedOption.Value!.Value);
                    writer.WriteString("team_parsed", teamParsedRawValue);
                }
                else
                    writer.WriteNull("team_parsed");
        }
    }
}
