// <auto-generated>
/*
 * Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using DeadlockApiClient.Client;

namespace DeadlockApiClient.Model
{
    /// <summary>
    /// Defines ESportsMatchStatus
    /// </summary>
    public enum ESportsMatchStatus
    {
        /// <summary>
        /// Enum Live for value: Live
        /// </summary>
        Live = 1,

        /// <summary>
        /// Enum Completed for value: Completed
        /// </summary>
        Completed = 2,

        /// <summary>
        /// Enum Scheduled for value: Scheduled
        /// </summary>
        Scheduled = 3,

        /// <summary>
        /// Enum Cancelled for value: Cancelled
        /// </summary>
        Cancelled = 4
    }

    /// <summary>
    /// Converts <see cref="ESportsMatchStatus"/> to and from the JSON value
    /// </summary>
    public static class ESportsMatchStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ESportsMatchStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ESportsMatchStatus FromString(string value)
        {
            if (value.Equals("Live"))
                return ESportsMatchStatus.Live;

            if (value.Equals("Completed"))
                return ESportsMatchStatus.Completed;

            if (value.Equals("Scheduled"))
                return ESportsMatchStatus.Scheduled;

            if (value.Equals("Cancelled"))
                return ESportsMatchStatus.Cancelled;

            throw new NotImplementedException($"Could not convert value to type ESportsMatchStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ESportsMatchStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ESportsMatchStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("Live"))
                return ESportsMatchStatus.Live;

            if (value.Equals("Completed"))
                return ESportsMatchStatus.Completed;

            if (value.Equals("Scheduled"))
                return ESportsMatchStatus.Scheduled;

            if (value.Equals("Cancelled"))
                return ESportsMatchStatus.Cancelled;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ESportsMatchStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ESportsMatchStatus value)
        {
            if (value == ESportsMatchStatus.Live)
                return "Live";

            if (value == ESportsMatchStatus.Completed)
                return "Completed";

            if (value == ESportsMatchStatus.Scheduled)
                return "Scheduled";

            if (value == ESportsMatchStatus.Cancelled)
                return "Cancelled";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ESportsMatchStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ESportsMatchStatusJsonConverter : JsonConverter<ESportsMatchStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ESportsMatchStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ESportsMatchStatus? result = rawValue == null
                ? null
                : ESportsMatchStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ESportsMatchStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eSportsMatchStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ESportsMatchStatus eSportsMatchStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ESportsMatchStatusValueConverter.ToJsonValue(eSportsMatchStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ESportsMatchStatus"/>
    /// </summary>
    public class ESportsMatchStatusNullableJsonConverter : JsonConverter<ESportsMatchStatus?>
    {
        /// <summary>
        /// Returns a ESportsMatchStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ESportsMatchStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ESportsMatchStatus? result = rawValue == null
                ? null
                : ESportsMatchStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ESportsMatchStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eSportsMatchStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ESportsMatchStatus? eSportsMatchStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eSportsMatchStatus.HasValue ? ESportsMatchStatusValueConverter.ToJsonValue(eSportsMatchStatus.Value).ToString() : "null");
        }
    }
}
