/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HashMap } from "./HashMap.ts";

export type PlayerStatsMetricsQueryParams = {
    /**
     * @description Filter matches based on the hero IDs. See more: <https://assets.deadlock-api.com/v2/heroes>
     * @type string,null | undefined
    */
    hero_ids?: string | null;
    /**
     * @description Filter matches based on their start time (Unix timestamp). **Default:** 30 days ago.
     * @default 1754092800
     * @type integer,null | undefined, int64
    */
    min_unix_timestamp?: number | null;
    /**
     * @description Filter matches based on their start time (Unix timestamp).
     * @type integer,null | undefined, int64
    */
    max_unix_timestamp?: number | null;
    /**
     * @description Filter matches based on their duration in seconds (up to 7000s).
     * @minLength 0
     * @maxLength 7000
     * @type integer,null | undefined, int64
    */
    min_duration_s?: number | null;
    /**
     * @description Filter matches based on their duration in seconds (up to 7000s).
     * @minLength 0
     * @maxLength 7000
     * @type integer,null | undefined, int64
    */
    max_duration_s?: number | null;
    /**
     * @description Filter players based on their net worth.
     * @minLength 0
     * @type integer,null | undefined, int64
    */
    min_networth?: number | null;
    /**
     * @description Filter players based on their net worth.
     * @minLength 0
     * @type integer,null | undefined, int64
    */
    max_networth?: number | null;
    /**
     * @description Filter matches based on the average badge level (0-116) of *both* teams involved. See more: <https://assets.deadlock-api.com/v2/ranks>
     * @minLength 0
     * @maxLength 116
     * @type integer,null | undefined, int32
    */
    min_average_badge?: number | null;
    /**
     * @description Filter matches based on the average badge level (0-116) of *both* teams involved. See more: <https://assets.deadlock-api.com/v2/ranks>
     * @minLength 0
     * @maxLength 116
     * @type integer,null | undefined, int32
    */
    max_average_badge?: number | null;
    /**
     * @description Filter matches based on their ID.
     * @minLength 0
     * @type integer,null | undefined, int64
    */
    min_match_id?: number | null;
    /**
     * @description Filter matches based on their ID.
     * @minLength 0
     * @type integer,null | undefined, int64
    */
    max_match_id?: number | null;
    /**
     * @description Comma separated list of item ids to include (only heroes who have purchased these items). See more: <https://assets.deadlock-api.com/v2/items>
     * @type array,null | undefined
    */
    include_item_ids?: number[] | null;
    /**
     * @description Comma separated list of item ids to exclude (only heroes who have not purchased these items). See more: <https://assets.deadlock-api.com/v2/items>
     * @type array,null | undefined
    */
    exclude_item_ids?: number[] | null;
    /**
     * @description Comma separated list of account ids to include
     * @type array,null | undefined
    */
    account_ids?: number[] | null;
};

/**
 * @description Hero Stats
*/
export type PlayerStatsMetrics200 = HashMap[];

/**
 * @description Provided parameters are invalid.
*/
export type PlayerStatsMetrics400 = any;

/**
 * @description Failed to fetch player stats metrics
*/
export type PlayerStatsMetrics500 = any;

export type PlayerStatsMetricsQueryResponse = PlayerStatsMetrics200;

export type PlayerStatsMetricsQuery = {
    Response: PlayerStatsMetrics200;
    QueryParams: PlayerStatsMetricsQueryParams;
    Errors: PlayerStatsMetrics400 | PlayerStatsMetrics500;
};