/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package assets_deadlock_api_client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import assets_deadlock_api_client.models.AbilityVideosV2

class AbilityVideosV2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of AbilityVideosV2
        //val modelInstance = AbilityVideosV2()

        // to test the property `webm`
        should("test webm") {
            // uncomment below to test the property
            //modelInstance.webm shouldBe ("TODO")
        }

        // to test the property `mp4`
        should("test mp4") {
            // uncomment below to test the property
            //modelInstance.mp4 shouldBe ("TODO")
        }

    }
}
