/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package assets_deadlock_api_client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import assets_deadlock_api_client.models.SubclassRangedArmorModifier
import assets_deadlock_api_client.models.RangedArmorModifier

class SubclassRangedArmorModifierTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubclassRangedArmorModifier
        //val modelInstance = SubclassRangedArmorModifier()

        // to test the property `subclass`
        should("test subclass") {
            // uncomment below to test the property
            //modelInstance.subclass shouldBe ("TODO")
        }

    }
}
