/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package deadlock_api_client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import deadlock_api_client.models.VariableDescription
import deadlock_api_client.models.VariableCategory

class VariableDescriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VariableDescription
        //val modelInstance = VariableDescription()

        // to test the property `category` - The category of the variable.
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `description` - The description of the variable.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `extraArgs` - Extra arguments that can be passed to the variable.
        should("test extraArgs") {
            // uncomment below to test the property
            //modelInstance.extraArgs shouldBe ("TODO")
        }

        // to test the property `name` - The name of the variable.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `defaultLabel` - The default label for the variable.
        should("test defaultLabel") {
            // uncomment below to test the property
            //modelInstance.defaultLabel shouldBe ("TODO")
        }

    }
}
