/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package deadlock-api-client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import deadlock-api-client.apis.InfoApi
import deadlock-api-client.models.APIInfo
import deadlock-api-client.models.Status

class InfoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InfoApi
        //val apiInstance = InfoApi()

        // to test healthCheck
        should("test healthCheck") {
            // uncomment below to test healthCheck
            //val result : Status = apiInstance.healthCheck()
            //result shouldBe ("TODO")
        }

        // to test info
        should("test info") {
            // uncomment below to test info
            //val result : APIInfo = apiInstance.info()
            //result shouldBe ("TODO")
        }

    }
}
