## DefaultApi

### Get Build Tags
## Get Build Tags
GET https://assets.deadlock-api.com/v2/build-tags?language={{language}}&clientVersion={{clientVersion}}
Accept: application/json

### Get Client Versions
## Get Client Versions
GET https://assets.deadlock-api.com/v2/client-versions
Accept: application/json

### Get Colors
## Get Colors
GET https://assets.deadlock-api.com/v1/colors?clientVersion={{clientVersion}}
Accept: application/json

### Get Generic Data
## Get Generic Data
GET https://assets.deadlock-api.com/v2/generic-data?clientVersion={{clientVersion}}
Accept: application/json

### Get Icons
## Get Icons
GET https://assets.deadlock-api.com/v1/icons?clientVersion={{clientVersion}}
Accept: application/json

### Get Images
## Get Images
GET https://assets.deadlock-api.com/v1/images?clientVersion={{clientVersion}}
Accept: application/json

### Get Loot Tables
## Get Loot Tables
GET https://assets.deadlock-api.com/v2/loot-tables?clientVersion={{clientVersion}}
Accept: application/json

### Get Map
## Get Map
GET https://assets.deadlock-api.com/v1/map?clientVersion={{clientVersion}}
Accept: application/json

### Get Ranks
## Get Ranks
GET https://assets.deadlock-api.com/v2/ranks?language={{language}}&clientVersion={{clientVersion}}
Accept: application/json

### Get Sounds
## Get Sounds
GET https://assets.deadlock-api.com/v1/sounds?clientVersion={{clientVersion}}
Accept: application/json

### Get Steam Info
## Get Steam Info
GET https://assets.deadlock-api.com/v1/steam-info?clientVersion={{clientVersion}}
Accept: application/json
