## RawApi

### Get Raw Heroes
## Get Raw Heroes
GET https://assets.deadlock-api.com/raw/heroes?clientVersion={{clientVersion}}
Accept: application/json

### Get Raw Items
## Get Raw Items
GET https://assets.deadlock-api.com/raw/items?clientVersion={{clientVersion}}
Accept: application/json
