from enum import Enum


class HeroScoreboardSortBy(str, Enum):
    ASSISTS = "assists"
    AVG_ASSISTS_PER_MATCH = "avg_assists_per_match"
    AVG_BOSS_DAMAGE_PER_MATCH = "avg_boss_damage_per_match"
    AVG_CREEP_DAMAGE_PER_MATCH = "avg_creep_damage_per_match"
    AVG_CREEP_KILLS_PER_MATCH = "avg_creep_kills_per_match"
    AVG_DAMAGE_TAKEN_PER_MATCH = "avg_damage_taken_per_match"
    AVG_DEATHS_PER_MATCH = "avg_deaths_per_match"
    AVG_DENIES_PER_MATCH = "avg_denies_per_match"
    AVG_HERO_BULLETS_HIT_CRIT_PER_MATCH = "avg_hero_bullets_hit_crit_per_match"
    AVG_HERO_BULLETS_HIT_PER_MATCH = "avg_hero_bullets_hit_per_match"
    AVG_KILLS_PER_MATCH = "avg_kills_per_match"
    AVG_LAST_HITS_PER_MATCH = "avg_last_hits_per_match"
    AVG_MAX_HEALTH_PER_MATCH = "avg_max_health_per_match"
    AVG_NET_WORTH_PER_MATCH = "avg_net_worth_per_match"
    AVG_NEUTRAL_DAMAGE_PER_MATCH = "avg_neutral_damage_per_match"
    AVG_NEUTRAL_KILLS_PER_MATCH = "avg_neutral_kills_per_match"
    AVG_PLAYER_DAMAGE_PER_MATCH = "avg_player_damage_per_match"
    AVG_PLAYER_LEVEL_PER_MATCH = "avg_player_level_per_match"
    AVG_SHOTS_HIT_PER_MATCH = "avg_shots_hit_per_match"
    AVG_SHOTS_MISSED_PER_MATCH = "avg_shots_missed_per_match"
    BOSS_DAMAGE = "boss_damage"
    CREEP_DAMAGE = "creep_damage"
    CREEP_KILLS = "creep_kills"
    DAMAGE_TAKEN = "damage_taken"
    DEATHS = "deaths"
    DENIES = "denies"
    HERO_BULLETS_HIT = "hero_bullets_hit"
    HERO_BULLETS_HIT_CRIT = "hero_bullets_hit_crit"
    KILLS = "kills"
    LAST_HITS = "last_hits"
    LOSSES = "losses"
    MATCHES = "matches"
    MAX_ASSISTS_PER_MATCH = "max_assists_per_match"
    MAX_BOSS_DAMAGE_PER_MATCH = "max_boss_damage_per_match"
    MAX_CREEP_DAMAGE_PER_MATCH = "max_creep_damage_per_match"
    MAX_CREEP_KILLS_PER_MATCH = "max_creep_kills_per_match"
    MAX_DAMAGE_TAKEN_PER_MATCH = "max_damage_taken_per_match"
    MAX_DEATHS_PER_MATCH = "max_deaths_per_match"
    MAX_DENIES_PER_MATCH = "max_denies_per_match"
    MAX_HEALTH = "max_health"
    MAX_HERO_BULLETS_HIT_CRIT_PER_MATCH = "max_hero_bullets_hit_crit_per_match"
    MAX_HERO_BULLETS_HIT_PER_MATCH = "max_hero_bullets_hit_per_match"
    MAX_KILLS_PER_MATCH = "max_kills_per_match"
    MAX_LAST_HITS_PER_MATCH = "max_last_hits_per_match"
    MAX_MAX_HEALTH_PER_MATCH = "max_max_health_per_match"
    MAX_NET_WORTH_PER_MATCH = "max_net_worth_per_match"
    MAX_NEUTRAL_DAMAGE_PER_MATCH = "max_neutral_damage_per_match"
    MAX_NEUTRAL_KILLS_PER_MATCH = "max_neutral_kills_per_match"
    MAX_PLAYER_DAMAGE_PER_MATCH = "max_player_damage_per_match"
    MAX_PLAYER_LEVEL_PER_MATCH = "max_player_level_per_match"
    MAX_SHOTS_HIT_PER_MATCH = "max_shots_hit_per_match"
    MAX_SHOTS_MISSED_PER_MATCH = "max_shots_missed_per_match"
    NET_WORTH = "net_worth"
    NEUTRAL_DAMAGE = "neutral_damage"
    NEUTRAL_KILLS = "neutral_kills"
    PLAYER_DAMAGE = "player_damage"
    PLAYER_LEVEL = "player_level"
    SHOTS_HIT = "shots_hit"
    SHOTS_MISSED = "shots_missed"
    WINRATE = "winrate"
    WINS = "wins"

    def __str__(self) -> str:
        return str(self.value)
