// <auto-generated>
/*
 * Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using DeadlockApiClient.Client;

namespace DeadlockApiClient.Model
{
    /// <summary>
    /// CorruptedPenaltyEffect
    /// </summary>
    public partial class CorruptedPenaltyEffect : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CorruptedPenaltyEffect" /> class.
        /// </summary>
        /// <param name="bonusPerTier">Penalty value indexed by item tier (same indexing as &#x60;item_price_per_tier&#x60;; tiers that can&#39;t be corrupted are &#x60;0&#x60;), in display units: distances are meters (source suffix &#x60;m&#x60; stripped), matching &#x60;postfix&#x60;.</param>
        /// <param name="display">&#x60;false&#x60; for effects the game applies but doesn&#39;t list in tooltips.</param>
        /// <param name="modifierValue">Modifier the penalty applies, e.g. &#x60;MODIFIER_VALUE_COOLDOWN_REDUCTION_PERCENTAGE&#x60;.</param>
        /// <param name="cssClass">cssClass</param>
        /// <param name="displayType">displayType</param>
        /// <param name="label">Localized stat label (from &#x60;loc_token_override&#x60;).</param>
        /// <param name="locTokenOverride">locTokenOverride</param>
        /// <param name="postfix">Localized unit suffix, e.g. &#x60;%&#x60; or &#x60; m&#x60;.</param>
        [JsonConstructor]
        public CorruptedPenaltyEffect(List<double> bonusPerTier, bool display, string modifierValue, Option<string?> cssClass = default, Option<string?> displayType = default, Option<string?> label = default, Option<string?> locTokenOverride = default, Option<string?> postfix = default)
        {
            BonusPerTier = bonusPerTier;
            Display = display;
            ModifierValue = modifierValue;
            CssClassOption = cssClass;
            DisplayTypeOption = displayType;
            LabelOption = label;
            LocTokenOverrideOption = locTokenOverride;
            PostfixOption = postfix;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Penalty value indexed by item tier (same indexing as &#x60;item_price_per_tier&#x60;; tiers that can&#39;t be corrupted are &#x60;0&#x60;), in display units: distances are meters (source suffix &#x60;m&#x60; stripped), matching &#x60;postfix&#x60;.
        /// </summary>
        /// <value>Penalty value indexed by item tier (same indexing as &#x60;item_price_per_tier&#x60;; tiers that can&#39;t be corrupted are &#x60;0&#x60;), in display units: distances are meters (source suffix &#x60;m&#x60; stripped), matching &#x60;postfix&#x60;.</value>
        [JsonPropertyName("bonus_per_tier")]
        public List<double> BonusPerTier { get; set; }

        /// <summary>
        /// &#x60;false&#x60; for effects the game applies but doesn&#39;t list in tooltips.
        /// </summary>
        /// <value>&#x60;false&#x60; for effects the game applies but doesn&#39;t list in tooltips.</value>
        [JsonPropertyName("display")]
        public bool Display { get; set; }

        /// <summary>
        /// Modifier the penalty applies, e.g. &#x60;MODIFIER_VALUE_COOLDOWN_REDUCTION_PERCENTAGE&#x60;.
        /// </summary>
        /// <value>Modifier the penalty applies, e.g. &#x60;MODIFIER_VALUE_COOLDOWN_REDUCTION_PERCENTAGE&#x60;.</value>
        [JsonPropertyName("modifier_value")]
        public string ModifierValue { get; set; }

        /// <summary>
        /// Used to track the state of CssClass
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CssClassOption { get; private set; }

        /// <summary>
        /// Gets or Sets CssClass
        /// </summary>
        [JsonPropertyName("css_class")]
        public string? CssClass { get { return this.CssClassOption.Value; } set { this.CssClassOption = new(value); } }

        /// <summary>
        /// Used to track the state of DisplayType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DisplayTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisplayType
        /// </summary>
        [JsonPropertyName("display_type")]
        public string? DisplayType { get { return this.DisplayTypeOption.Value; } set { this.DisplayTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Label
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LabelOption { get; private set; }

        /// <summary>
        /// Localized stat label (from &#x60;loc_token_override&#x60;).
        /// </summary>
        /// <value>Localized stat label (from &#x60;loc_token_override&#x60;).</value>
        [JsonPropertyName("label")]
        public string? Label { get { return this.LabelOption.Value; } set { this.LabelOption = new(value); } }

        /// <summary>
        /// Used to track the state of LocTokenOverride
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LocTokenOverrideOption { get; private set; }

        /// <summary>
        /// Gets or Sets LocTokenOverride
        /// </summary>
        [JsonPropertyName("loc_token_override")]
        public string? LocTokenOverride { get { return this.LocTokenOverrideOption.Value; } set { this.LocTokenOverrideOption = new(value); } }

        /// <summary>
        /// Used to track the state of Postfix
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PostfixOption { get; private set; }

        /// <summary>
        /// Localized unit suffix, e.g. &#x60;%&#x60; or &#x60; m&#x60;.
        /// </summary>
        /// <value>Localized unit suffix, e.g. &#x60;%&#x60; or &#x60; m&#x60;.</value>
        [JsonPropertyName("postfix")]
        public string? Postfix { get { return this.PostfixOption.Value; } set { this.PostfixOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CorruptedPenaltyEffect {\n");
            sb.Append("  BonusPerTier: ").Append(BonusPerTier).Append("\n");
            sb.Append("  Display: ").Append(Display).Append("\n");
            sb.Append("  ModifierValue: ").Append(ModifierValue).Append("\n");
            sb.Append("  CssClass: ").Append(CssClass).Append("\n");
            sb.Append("  DisplayType: ").Append(DisplayType).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  LocTokenOverride: ").Append(LocTokenOverride).Append("\n");
            sb.Append("  Postfix: ").Append(Postfix).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CorruptedPenaltyEffect" />
    /// </summary>
    public partial class CorruptedPenaltyEffectJsonConverter : JsonConverter<CorruptedPenaltyEffect>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CorruptedPenaltyEffectJsonConverter" /> class.
        /// </summary>
        public CorruptedPenaltyEffectJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CorruptedPenaltyEffect" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CorruptedPenaltyEffect Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<double>?> bonusPerTier = default;
            Option<bool?> display = default;
            Option<string?> modifierValue = default;
            Option<string?> cssClass = default;
            Option<string?> displayType = default;
            Option<string?> label = default;
            Option<string?> locTokenOverride = default;
            Option<string?> postfix = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bonus_per_tier":
                            bonusPerTier = new Option<List<double>?>(JsonSerializer.Deserialize<List<double>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "display":
                            display = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "modifier_value":
                            modifierValue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "css_class":
                            cssClass = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "display_type":
                            displayType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "loc_token_override":
                            locTokenOverride = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "postfix":
                            postfix = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!bonusPerTier.IsSet)
                throw new JsonException("Property is required for class CorruptedPenaltyEffect: bonus_per_tier.");

            if (!display.IsSet)
                throw new JsonException("Property is required for class CorruptedPenaltyEffect: display.");

            if (!modifierValue.IsSet)
                throw new JsonException("Property is required for class CorruptedPenaltyEffect: modifier_value.");

            if (bonusPerTier.IsSet && bonusPerTier.Value == null)
                throw new JsonException("Property is not nullable for class CorruptedPenaltyEffect: bonus_per_tier.");

            if (display.IsSet && display.Value == null)
                throw new JsonException("Property is not nullable for class CorruptedPenaltyEffect: display.");

            if (modifierValue.IsSet && modifierValue.Value == null)
                throw new JsonException("Property is not nullable for class CorruptedPenaltyEffect: modifier_value.");

            return new CorruptedPenaltyEffect(bonusPerTier.Value!, display.Value!.Value!, modifierValue.Value!, cssClass, displayType, label, locTokenOverride, postfix);
        }

        /// <summary>
        /// Serializes a <see cref="CorruptedPenaltyEffect" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="corruptedPenaltyEffect"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, CorruptedPenaltyEffect corruptedPenaltyEffect, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, corruptedPenaltyEffect, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CorruptedPenaltyEffect" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="corruptedPenaltyEffect"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, CorruptedPenaltyEffect corruptedPenaltyEffect, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WritePropertyName("bonus_per_tier");
            JsonSerializer.Serialize(writer, corruptedPenaltyEffect.BonusPerTier, jsonSerializerOptions);
            writer.WriteBoolean("display", corruptedPenaltyEffect.Display);

            writer.WriteString("modifier_value", corruptedPenaltyEffect.ModifierValue);

            if (corruptedPenaltyEffect.CssClassOption.IsSet)
                if (corruptedPenaltyEffect.CssClassOption.Value != null)
                    writer.WriteString("css_class", corruptedPenaltyEffect.CssClass);
                else
                    writer.WriteNull("css_class");

            if (corruptedPenaltyEffect.DisplayTypeOption.IsSet)
                if (corruptedPenaltyEffect.DisplayTypeOption.Value != null)
                    writer.WriteString("display_type", corruptedPenaltyEffect.DisplayType);
                else
                    writer.WriteNull("display_type");

            if (corruptedPenaltyEffect.LabelOption.IsSet)
                if (corruptedPenaltyEffect.LabelOption.Value != null)
                    writer.WriteString("label", corruptedPenaltyEffect.Label);
                else
                    writer.WriteNull("label");

            if (corruptedPenaltyEffect.LocTokenOverrideOption.IsSet)
                if (corruptedPenaltyEffect.LocTokenOverrideOption.Value != null)
                    writer.WriteString("loc_token_override", corruptedPenaltyEffect.LocTokenOverride);
                else
                    writer.WriteNull("loc_token_override");

            if (corruptedPenaltyEffect.PostfixOption.IsSet)
                if (corruptedPenaltyEffect.PostfixOption.Value != null)
                    writer.WriteString("postfix", corruptedPenaltyEffect.Postfix);
                else
                    writer.WriteNull("postfix");
        }
    }
}
