// <auto-generated>
/*
 * Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using DeadlockApiClient.Client;

namespace DeadlockApiClient.Model
{
    /// <summary>
    /// A penalty that can be rolled onto a corrupted item (build 6711+).
    /// </summary>
    public partial class CorruptedPenalty : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CorruptedPenalty" /> class.
        /// </summary>
        /// <param name="effects">effects</param>
        /// <param name="name">name</param>
        /// <param name="rollWeight">rollWeight</param>
        [JsonConstructor]
        public CorruptedPenalty(List<CorruptedPenaltyEffect> effects, string name, Option<double?> rollWeight = default)
        {
            Effects = effects;
            Name = name;
            RollWeightOption = rollWeight;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Effects
        /// </summary>
        [JsonPropertyName("effects")]
        public List<CorruptedPenaltyEffect> Effects { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of RollWeight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> RollWeightOption { get; private set; }

        /// <summary>
        /// Gets or Sets RollWeight
        /// </summary>
        [JsonPropertyName("roll_weight")]
        public double? RollWeight { get { return this.RollWeightOption.Value; } set { this.RollWeightOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CorruptedPenalty {\n");
            sb.Append("  Effects: ").Append(Effects).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RollWeight: ").Append(RollWeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CorruptedPenalty" />
    /// </summary>
    public partial class CorruptedPenaltyJsonConverter : JsonConverter<CorruptedPenalty>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CorruptedPenaltyJsonConverter" /> class.
        /// </summary>
        public CorruptedPenaltyJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CorruptedPenalty" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CorruptedPenalty Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<CorruptedPenaltyEffect>?> effects = default;
            Option<string?> name = default;
            Option<double?> rollWeight = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "effects":
                            effects = new Option<List<CorruptedPenaltyEffect>?>(JsonSerializer.Deserialize<List<CorruptedPenaltyEffect>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "roll_weight":
                            rollWeight = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!effects.IsSet)
                throw new ArgumentException("Property is required for class CorruptedPenalty.", nameof(effects));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CorruptedPenalty.", nameof(name));

            if (effects.IsSet && effects.Value == null)
                throw new ArgumentNullException(nameof(effects), "Property is not nullable for class CorruptedPenalty.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CorruptedPenalty.");

            return new CorruptedPenalty(effects.Value!, name.Value!, rollWeight);
        }

        /// <summary>
        /// Serializes a <see cref="CorruptedPenalty" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="corruptedPenalty"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CorruptedPenalty corruptedPenalty, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, corruptedPenalty, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CorruptedPenalty" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="corruptedPenalty"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CorruptedPenalty corruptedPenalty, JsonSerializerOptions jsonSerializerOptions)
        {
            if (corruptedPenalty.Effects == null)
                throw new ArgumentNullException(nameof(corruptedPenalty.Effects), "Property is required for class CorruptedPenalty.");

            if (corruptedPenalty.Name == null)
                throw new ArgumentNullException(nameof(corruptedPenalty.Name), "Property is required for class CorruptedPenalty.");

            writer.WritePropertyName("effects");
            JsonSerializer.Serialize(writer, corruptedPenalty.Effects, jsonSerializerOptions);
            writer.WriteString("name", corruptedPenalty.Name);

            if (corruptedPenalty.RollWeightOption.IsSet)
                if (corruptedPenalty.RollWeightOption.Value != null)
                    writer.WriteNumber("roll_weight", corruptedPenalty.RollWeightOption.Value!.Value);
                else
                    writer.WriteNull("roll_weight");
        }
    }
}
