/*
Deadlock API

Testing BuildTagsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package deadlock_api_client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/deadlock-api/openapi-clients"
)

func Test_deadlock_api_client_BuildTagsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BuildTagsAPIService GetBuildTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildTagId int32

		resp, httpRes, err := apiClient.BuildTagsAPI.GetBuildTag(context.Background(), buildTagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildTagsAPIService GetBuildTagByName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.BuildTagsAPI.GetBuildTagByName(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildTagsAPIService ListBuildTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BuildTagsAPI.ListBuildTags(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
