/*
 * Assets - Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SteamInfoV1 {
    #[serde(rename = "client_version")]
    pub client_version: i32,
    #[serde(rename = "server_version")]
    pub server_version: i32,
    #[serde(rename = "product_name")]
    pub product_name: String,
    #[serde(rename = "app_id")]
    pub app_id: i32,
    #[serde(rename = "server_app_id")]
    pub server_app_id: i32,
    #[serde(rename = "tools_app_id")]
    pub tools_app_id: i32,
    #[serde(rename = "source_revision")]
    pub source_revision: i32,
    #[serde(rename = "version_date")]
    pub version_date: String,
    #[serde(rename = "version_time")]
    pub version_time: String,
    #[serde(rename = "version_datetime")]
    pub version_datetime: String,
}

impl SteamInfoV1 {
    pub fn new(client_version: i32, server_version: i32, product_name: String, app_id: i32, server_app_id: i32, tools_app_id: i32, source_revision: i32, version_date: String, version_time: String, version_datetime: String) -> SteamInfoV1 {
        SteamInfoV1 {
            client_version,
            server_version,
            product_name,
            app_id,
            server_app_id,
            tools_app_id,
            source_revision,
            version_date,
            version_time,
            version_datetime,
        }
    }
}

