<?php
/**
 * CreateCustomRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock API
 *
 * ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CreateCustomRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateCustomRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateCustomRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'callback_url' => 'string',
        'cheats_enabled' => 'bool',
        'duplicate_heroes_enabled' => 'bool',
        'experimental_heroes_enabled' => 'bool',
        'is_publicly_visible' => 'bool',
        'min_roster_size' => 'int',
        'randomize_lanes' => 'bool',
        'region_mode' => '\OpenAPI\Client\Model\RegionMode'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'callback_url' => null,
        'cheats_enabled' => null,
        'duplicate_heroes_enabled' => null,
        'experimental_heroes_enabled' => null,
        'is_publicly_visible' => null,
        'min_roster_size' => 'int32',
        'randomize_lanes' => null,
        'region_mode' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'callback_url' => true,
        'cheats_enabled' => true,
        'duplicate_heroes_enabled' => true,
        'experimental_heroes_enabled' => true,
        'is_publicly_visible' => true,
        'min_roster_size' => true,
        'randomize_lanes' => true,
        'region_mode' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'callback_url' => 'callback_url',
        'cheats_enabled' => 'cheats_enabled',
        'duplicate_heroes_enabled' => 'duplicate_heroes_enabled',
        'experimental_heroes_enabled' => 'experimental_heroes_enabled',
        'is_publicly_visible' => 'is_publicly_visible',
        'min_roster_size' => 'min_roster_size',
        'randomize_lanes' => 'randomize_lanes',
        'region_mode' => 'region_mode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'callback_url' => 'setCallbackUrl',
        'cheats_enabled' => 'setCheatsEnabled',
        'duplicate_heroes_enabled' => 'setDuplicateHeroesEnabled',
        'experimental_heroes_enabled' => 'setExperimentalHeroesEnabled',
        'is_publicly_visible' => 'setIsPubliclyVisible',
        'min_roster_size' => 'setMinRosterSize',
        'randomize_lanes' => 'setRandomizeLanes',
        'region_mode' => 'setRegionMode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'callback_url' => 'getCallbackUrl',
        'cheats_enabled' => 'getCheatsEnabled',
        'duplicate_heroes_enabled' => 'getDuplicateHeroesEnabled',
        'experimental_heroes_enabled' => 'getExperimentalHeroesEnabled',
        'is_publicly_visible' => 'getIsPubliclyVisible',
        'min_roster_size' => 'getMinRosterSize',
        'randomize_lanes' => 'getRandomizeLanes',
        'region_mode' => 'getRegionMode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('cheats_enabled', $data ?? [], null);
        $this->setIfExists('duplicate_heroes_enabled', $data ?? [], null);
        $this->setIfExists('experimental_heroes_enabled', $data ?? [], null);
        $this->setIfExists('is_publicly_visible', $data ?? [], null);
        $this->setIfExists('min_roster_size', $data ?? [], null);
        $this->setIfExists('randomize_lanes', $data ?? [], null);
        $this->setIfExists('region_mode', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['min_roster_size']) && ($this->container['min_roster_size'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_roster_size', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url If a callback url is provided, we will send a POST request to this url when the match starts.
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            array_push($this->openAPINullablesSetToNull, 'callback_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('callback_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets cheats_enabled
     *
     * @return bool|null
     */
    public function getCheatsEnabled()
    {
        return $this->container['cheats_enabled'];
    }

    /**
     * Sets cheats_enabled
     *
     * @param bool|null $cheats_enabled cheats_enabled
     *
     * @return self
     */
    public function setCheatsEnabled($cheats_enabled)
    {
        if (is_null($cheats_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'cheats_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cheats_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cheats_enabled'] = $cheats_enabled;

        return $this;
    }

    /**
     * Gets duplicate_heroes_enabled
     *
     * @return bool|null
     */
    public function getDuplicateHeroesEnabled()
    {
        return $this->container['duplicate_heroes_enabled'];
    }

    /**
     * Sets duplicate_heroes_enabled
     *
     * @param bool|null $duplicate_heroes_enabled duplicate_heroes_enabled
     *
     * @return self
     */
    public function setDuplicateHeroesEnabled($duplicate_heroes_enabled)
    {
        if (is_null($duplicate_heroes_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'duplicate_heroes_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('duplicate_heroes_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['duplicate_heroes_enabled'] = $duplicate_heroes_enabled;

        return $this;
    }

    /**
     * Gets experimental_heroes_enabled
     *
     * @return bool|null
     */
    public function getExperimentalHeroesEnabled()
    {
        return $this->container['experimental_heroes_enabled'];
    }

    /**
     * Sets experimental_heroes_enabled
     *
     * @param bool|null $experimental_heroes_enabled experimental_heroes_enabled
     *
     * @return self
     */
    public function setExperimentalHeroesEnabled($experimental_heroes_enabled)
    {
        if (is_null($experimental_heroes_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'experimental_heroes_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('experimental_heroes_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['experimental_heroes_enabled'] = $experimental_heroes_enabled;

        return $this;
    }

    /**
     * Gets is_publicly_visible
     *
     * @return bool|null
     */
    public function getIsPubliclyVisible()
    {
        return $this->container['is_publicly_visible'];
    }

    /**
     * Sets is_publicly_visible
     *
     * @param bool|null $is_publicly_visible is_publicly_visible
     *
     * @return self
     */
    public function setIsPubliclyVisible($is_publicly_visible)
    {
        if (is_null($is_publicly_visible)) {
            array_push($this->openAPINullablesSetToNull, 'is_publicly_visible');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_publicly_visible', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_publicly_visible'] = $is_publicly_visible;

        return $this;
    }

    /**
     * Gets min_roster_size
     *
     * @return int|null
     */
    public function getMinRosterSize()
    {
        return $this->container['min_roster_size'];
    }

    /**
     * Sets min_roster_size
     *
     * @param int|null $min_roster_size min_roster_size
     *
     * @return self
     */
    public function setMinRosterSize($min_roster_size)
    {
        if (is_null($min_roster_size)) {
            array_push($this->openAPINullablesSetToNull, 'min_roster_size');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_roster_size', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($min_roster_size) && ($min_roster_size < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_roster_size when calling CreateCustomRequest., must be bigger than or equal to 0.');
        }

        $this->container['min_roster_size'] = $min_roster_size;

        return $this;
    }

    /**
     * Gets randomize_lanes
     *
     * @return bool|null
     */
    public function getRandomizeLanes()
    {
        return $this->container['randomize_lanes'];
    }

    /**
     * Sets randomize_lanes
     *
     * @param bool|null $randomize_lanes randomize_lanes
     *
     * @return self
     */
    public function setRandomizeLanes($randomize_lanes)
    {
        if (is_null($randomize_lanes)) {
            array_push($this->openAPINullablesSetToNull, 'randomize_lanes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('randomize_lanes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['randomize_lanes'] = $randomize_lanes;

        return $this;
    }

    /**
     * Gets region_mode
     *
     * @return \OpenAPI\Client\Model\RegionMode|null
     */
    public function getRegionMode()
    {
        return $this->container['region_mode'];
    }

    /**
     * Sets region_mode
     *
     * @param \OpenAPI\Client\Model\RegionMode|null $region_mode region_mode
     *
     * @return self
     */
    public function setRegionMode($region_mode)
    {
        if (is_null($region_mode)) {
            array_push($this->openAPINullablesSetToNull, 'region_mode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('region_mode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['region_mode'] = $region_mode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


