/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HeroColorsV2 } from './HeroColorsV2.ts'
import type { HeroDescriptionV2 } from './HeroDescriptionV2.ts'
import type { HeroImagesV2 } from './HeroImagesV2.ts'
import type { HeroLevelInfoV2 } from './HeroLevelInfoV2.ts'
import type { HeroPhysicsV2 } from './HeroPhysicsV2.ts'
import type { HeroShopStatDisplayV2 } from './HeroShopStatDisplayV2.ts'
import type { HeroStartingStatsV2 } from './HeroStartingStatsV2.ts'
import type { HeroTypeV2 } from './HeroTypeV2.ts'
import type { RawHeroItemSlotInfoValueV2 } from './RawHeroItemSlotInfoValueV2.ts'
import type { RawHeroMapModCostBonusesV2 } from './RawHeroMapModCostBonusesV2.ts'
import type { RawHeroPurchaseBonusV2 } from './RawHeroPurchaseBonusV2.ts'
import type { RawHeroScalingStatV2 } from './RawHeroScalingStatV2.ts'
import type { RawHeroStatsDisplayV2 } from './RawHeroStatsDisplayV2.ts'
import type { RawHeroStatsUIV2 } from './RawHeroStatsUIV2.ts'

export type HeroV2 = {
  /**
   * @type integer
   */
  id: number
  /**
   * @type string
   */
  class_name: string
  /**
   * @type string
   */
  name: string
  /**
   * @type object
   */
  description: HeroDescriptionV2
  recommended_upgrades?: string[] | null
  recommended_ability_order?: string[] | null
  /**
   * @type boolean
   */
  player_selectable: boolean
  /**
   * @type boolean
   */
  disabled: boolean
  /**
   * @type boolean
   */
  in_development: boolean
  /**
   * @type boolean
   */
  needs_testing: boolean
  /**
   * @type boolean
   */
  assigned_players_only: boolean
  tags?: string[] | null
  gun_tag?: string | null
  hideout_rich_presence?: string | null
  hero_type?: HeroTypeV2 | null
  prerelease_only?: boolean | null
  /**
   * @type boolean
   */
  limited_testing: boolean
  /**
   * @type integer
   */
  complexity: number
  /**
   * @type integer
   */
  skin: number
  /**
   * @type object
   */
  images: HeroImagesV2
  /**
   * @type object
   */
  items: {
    [key: string]: string
  }
  /**
   * @type object
   */
  starting_stats: HeroStartingStatsV2
  /**
   * @type object
   */
  item_slot_info: {
    [key: string]: RawHeroItemSlotInfoValueV2
  }
  /**
   * @type object
   */
  physics: HeroPhysicsV2
  /**
   * @type object
   */
  colors: HeroColorsV2
  /**
   * @type object
   */
  shop_stat_display: HeroShopStatDisplayV2
  cost_bonuses?: {
    [key: string]: RawHeroMapModCostBonusesV2[]
  } | null
  /**
   * @type object
   */
  stats_display: RawHeroStatsDisplayV2
  /**
   * @type object
   */
  hero_stats_ui: RawHeroStatsUIV2
  /**
   * @type object
   */
  level_info: {
    [key: string]: HeroLevelInfoV2
  }
  /**
   * @type object
   */
  scaling_stats: {
    [key: string]: RawHeroScalingStatV2
  }
  /**
   * @type object
   */
  purchase_bonuses: {
    [key: string]: RawHeroPurchaseBonusV2[]
  }
  /**
   * @type object
   */
  standard_level_up_upgrades: {
    [key: string]: number
  }
}