/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package assets-deadlock-api-client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import assets-deadlock-api-client.models.RawItemWeaponInfoBulletSpeedCurveV2Output
import assets-deadlock-api-client.models.RawItemWeaponInfoBulletSpeedCurveSplineV2Output

class RawItemWeaponInfoBulletSpeedCurveV2OutputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RawItemWeaponInfoBulletSpeedCurveV2Output
        //val modelInstance = RawItemWeaponInfoBulletSpeedCurveV2Output()

        // to test the property `domainMaxs`
        should("test domainMaxs") {
            // uncomment below to test the property
            //modelInstance.domainMaxs shouldBe ("TODO")
        }

        // to test the property `domainMins`
        should("test domainMins") {
            // uncomment below to test the property
            //modelInstance.domainMins shouldBe ("TODO")
        }

        // to test the property `spline`
        should("test spline") {
            // uncomment below to test the property
            //modelInstance.spline shouldBe ("TODO")
        }

    }
}
