/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package assets-deadlock-api-client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import assets-deadlock-api-client.models.RawItemPropertyScaleFunctionSubclassV2Input

class RawItemPropertyScaleFunctionSubclassV2InputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RawItemPropertyScaleFunctionSubclassV2Input
        //val modelInstance = RawItemPropertyScaleFunctionSubclassV2Input()

        // to test the property `propertyClass`
        should("test propertyClass") {
            // uncomment below to test the property
            //modelInstance.propertyClass shouldBe ("TODO")
        }

        // to test the property `mySubclassName`
        should("test mySubclassName") {
            // uncomment below to test the property
            //modelInstance.mySubclassName shouldBe ("TODO")
        }

        // to test the property `mESpecificStatScaleType`
        should("test mESpecificStatScaleType") {
            // uncomment below to test the property
            //modelInstance.mESpecificStatScaleType shouldBe ("TODO")
        }

        // to test the property `mVecScalingStats`
        should("test mVecScalingStats") {
            // uncomment below to test the property
            //modelInstance.mVecScalingStats shouldBe ("TODO")
        }

        // to test the property `mFlStatScale`
        should("test mFlStatScale") {
            // uncomment below to test the property
            //modelInstance.mFlStatScale shouldBe ("TODO")
        }

    }
}
