// <auto-generated>
/*
 * Assets - Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AssetsDeadlockApiClient.Client;

namespace AssetsDeadlockApiClient.Model
{
    /// <summary>
    /// AbilityDescriptionV2
    /// </summary>
    public partial class AbilityDescriptionV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AbilityDescriptionV2" /> class.
        /// </summary>
        /// <param name="desc">desc</param>
        /// <param name="quip">quip</param>
        /// <param name="t1Desc">t1Desc</param>
        /// <param name="t2Desc">t2Desc</param>
        /// <param name="t3Desc">t3Desc</param>
        /// <param name="active">active</param>
        /// <param name="passive">passive</param>
        [JsonConstructor]
        public AbilityDescriptionV2(Option<string?> desc = default, Option<string?> quip = default, Option<string?> t1Desc = default, Option<string?> t2Desc = default, Option<string?> t3Desc = default, Option<string?> active = default, Option<string?> passive = default)
        {
            DescOption = desc;
            QuipOption = quip;
            T1DescOption = t1Desc;
            T2DescOption = t2Desc;
            T3DescOption = t3Desc;
            ActiveOption = active;
            PassiveOption = passive;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Desc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescOption { get; private set; }

        /// <summary>
        /// Gets or Sets Desc
        /// </summary>
        [JsonPropertyName("desc")]
        public string? Desc { get { return this.DescOption; } set { this.DescOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quip
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QuipOption { get; private set; }

        /// <summary>
        /// Gets or Sets Quip
        /// </summary>
        [JsonPropertyName("quip")]
        public string? Quip { get { return this.QuipOption; } set { this.QuipOption = new(value); } }

        /// <summary>
        /// Used to track the state of T1Desc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> T1DescOption { get; private set; }

        /// <summary>
        /// Gets or Sets T1Desc
        /// </summary>
        [JsonPropertyName("t1_desc")]
        public string? T1Desc { get { return this.T1DescOption; } set { this.T1DescOption = new(value); } }

        /// <summary>
        /// Used to track the state of T2Desc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> T2DescOption { get; private set; }

        /// <summary>
        /// Gets or Sets T2Desc
        /// </summary>
        [JsonPropertyName("t2_desc")]
        public string? T2Desc { get { return this.T2DescOption; } set { this.T2DescOption = new(value); } }

        /// <summary>
        /// Used to track the state of T3Desc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> T3DescOption { get; private set; }

        /// <summary>
        /// Gets or Sets T3Desc
        /// </summary>
        [JsonPropertyName("t3_desc")]
        public string? T3Desc { get { return this.T3DescOption; } set { this.T3DescOption = new(value); } }

        /// <summary>
        /// Used to track the state of Active
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [JsonPropertyName("active")]
        public string? Active { get { return this.ActiveOption; } set { this.ActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of Passive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PassiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets Passive
        /// </summary>
        [JsonPropertyName("passive")]
        public string? Passive { get { return this.PassiveOption; } set { this.PassiveOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AbilityDescriptionV2 {\n");
            sb.Append("  Desc: ").Append(Desc).Append("\n");
            sb.Append("  Quip: ").Append(Quip).Append("\n");
            sb.Append("  T1Desc: ").Append(T1Desc).Append("\n");
            sb.Append("  T2Desc: ").Append(T2Desc).Append("\n");
            sb.Append("  T3Desc: ").Append(T3Desc).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Passive: ").Append(Passive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AbilityDescriptionV2" />
    /// </summary>
    public class AbilityDescriptionV2JsonConverter : JsonConverter<AbilityDescriptionV2>
    {
        /// <summary>
        /// Deserializes json to <see cref="AbilityDescriptionV2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AbilityDescriptionV2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> desc = default;
            Option<string?> quip = default;
            Option<string?> t1Desc = default;
            Option<string?> t2Desc = default;
            Option<string?> t3Desc = default;
            Option<string?> active = default;
            Option<string?> passive = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "desc":
                            desc = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "quip":
                            quip = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "t1_desc":
                            t1Desc = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "t2_desc":
                            t2Desc = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "t3_desc":
                            t3Desc = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "active":
                            active = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "passive":
                            passive = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new AbilityDescriptionV2(desc, quip, t1Desc, t2Desc, t3Desc, active, passive);
        }

        /// <summary>
        /// Serializes a <see cref="AbilityDescriptionV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="abilityDescriptionV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AbilityDescriptionV2 abilityDescriptionV2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, abilityDescriptionV2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AbilityDescriptionV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="abilityDescriptionV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AbilityDescriptionV2 abilityDescriptionV2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (abilityDescriptionV2.DescOption.IsSet)
                if (abilityDescriptionV2.DescOption.Value != null)
                    writer.WriteString("desc", abilityDescriptionV2.Desc);
                else
                    writer.WriteNull("desc");

            if (abilityDescriptionV2.QuipOption.IsSet)
                if (abilityDescriptionV2.QuipOption.Value != null)
                    writer.WriteString("quip", abilityDescriptionV2.Quip);
                else
                    writer.WriteNull("quip");

            if (abilityDescriptionV2.T1DescOption.IsSet)
                if (abilityDescriptionV2.T1DescOption.Value != null)
                    writer.WriteString("t1_desc", abilityDescriptionV2.T1Desc);
                else
                    writer.WriteNull("t1_desc");

            if (abilityDescriptionV2.T2DescOption.IsSet)
                if (abilityDescriptionV2.T2DescOption.Value != null)
                    writer.WriteString("t2_desc", abilityDescriptionV2.T2Desc);
                else
                    writer.WriteNull("t2_desc");

            if (abilityDescriptionV2.T3DescOption.IsSet)
                if (abilityDescriptionV2.T3DescOption.Value != null)
                    writer.WriteString("t3_desc", abilityDescriptionV2.T3Desc);
                else
                    writer.WriteNull("t3_desc");

            if (abilityDescriptionV2.ActiveOption.IsSet)
                if (abilityDescriptionV2.ActiveOption.Value != null)
                    writer.WriteString("active", abilityDescriptionV2.Active);
                else
                    writer.WriteNull("active");

            if (abilityDescriptionV2.PassiveOption.IsSet)
                if (abilityDescriptionV2.PassiveOption.Value != null)
                    writer.WriteString("passive", abilityDescriptionV2.Passive);
                else
                    writer.WriteNull("passive");
        }
    }
}
