// <auto-generated>
/*
 * Assets - Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AssetsDeadlockApiClient.Client;

namespace AssetsDeadlockApiClient.Model
{
    /// <summary>
    /// GenericDataV2
    /// </summary>
    public partial class GenericDataV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericDataV2" /> class.
        /// </summary>
        /// <param name="damageFlash">damageFlash</param>
        /// <param name="glitchSettings">glitchSettings</param>
        /// <param name="laneInfo">laneInfo</param>
        /// <param name="newPlayerMetrics">newPlayerMetrics</param>
        /// <param name="itemPricePerTier">itemPricePerTier</param>
        /// <param name="trooperKillGoldShareFrac">trooperKillGoldShareFrac</param>
        /// <param name="heroKillGoldShareFrac">heroKillGoldShareFrac</param>
        /// <param name="aimSpringStrength">aimSpringStrength</param>
        /// <param name="targetingSpringStrength">targetingSpringStrength</param>
        /// <param name="objectiveParams">objectiveParams</param>
        /// <param name="rejuvParams">rejuvParams</param>
        /// <param name="miniMapOffsets">miniMapOffsets</param>
        /// <param name="weaponGroups">weaponGroups</param>
        /// <param name="armorGroups">armorGroups</param>
        /// <param name="spiritGroups">spiritGroups</param>
        /// <param name="minimapTeamRebelsColor">minimapTeamRebelsColor</param>
        /// <param name="minimapTeamCombineColor">minimapTeamCombineColor</param>
        /// <param name="enemyObjectivesAndZiplineColor">enemyObjectivesAndZiplineColor</param>
        /// <param name="enemyObjectivesColor">enemyObjectivesColor</param>
        /// <param name="enemyZiplineColor">enemyZiplineColor</param>
        /// <param name="streetBrawl">streetBrawl</param>
        [JsonConstructor]
        public GenericDataV2(DamageFlashV2 damageFlash, GlitchSettingsV2 glitchSettings, List<LaneInfoV2> laneInfo, List<NewPlayerMetricsV2> newPlayerMetrics, List<int> itemPricePerTier, List<decimal> trooperKillGoldShareFrac, List<decimal> heroKillGoldShareFrac, List<decimal> aimSpringStrength, List<decimal> targetingSpringStrength, ObjectiveParams objectiveParams, RejuvParams rejuvParams, List<MiniMapOffsets> miniMapOffsets, List<ItemGroup> weaponGroups, List<ItemGroup> armorGroups, List<ItemGroup> spiritGroups, Option<ColorV1?> minimapTeamRebelsColor = default, Option<ColorV1?> minimapTeamCombineColor = default, Option<ColorV1?> enemyObjectivesAndZiplineColor = default, Option<ColorV1?> enemyObjectivesColor = default, Option<ColorV1?> enemyZiplineColor = default, Option<StreetBrawl?> streetBrawl = default)
        {
            DamageFlash = damageFlash;
            GlitchSettings = glitchSettings;
            LaneInfo = laneInfo;
            NewPlayerMetrics = newPlayerMetrics;
            ItemPricePerTier = itemPricePerTier;
            TrooperKillGoldShareFrac = trooperKillGoldShareFrac;
            HeroKillGoldShareFrac = heroKillGoldShareFrac;
            AimSpringStrength = aimSpringStrength;
            TargetingSpringStrength = targetingSpringStrength;
            ObjectiveParams = objectiveParams;
            RejuvParams = rejuvParams;
            MiniMapOffsets = miniMapOffsets;
            WeaponGroups = weaponGroups;
            ArmorGroups = armorGroups;
            SpiritGroups = spiritGroups;
            MinimapTeamRebelsColorOption = minimapTeamRebelsColor;
            MinimapTeamCombineColorOption = minimapTeamCombineColor;
            EnemyObjectivesAndZiplineColorOption = enemyObjectivesAndZiplineColor;
            EnemyObjectivesColorOption = enemyObjectivesColor;
            EnemyZiplineColorOption = enemyZiplineColor;
            StreetBrawlOption = streetBrawl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets DamageFlash
        /// </summary>
        [JsonPropertyName("damage_flash")]
        public DamageFlashV2 DamageFlash { get; set; }

        /// <summary>
        /// Gets or Sets GlitchSettings
        /// </summary>
        [JsonPropertyName("glitch_settings")]
        public GlitchSettingsV2 GlitchSettings { get; set; }

        /// <summary>
        /// Gets or Sets LaneInfo
        /// </summary>
        [JsonPropertyName("lane_info")]
        public List<LaneInfoV2> LaneInfo { get; set; }

        /// <summary>
        /// Gets or Sets NewPlayerMetrics
        /// </summary>
        [JsonPropertyName("new_player_metrics")]
        public List<NewPlayerMetricsV2> NewPlayerMetrics { get; set; }

        /// <summary>
        /// Gets or Sets ItemPricePerTier
        /// </summary>
        [JsonPropertyName("item_price_per_tier")]
        public List<int> ItemPricePerTier { get; set; }

        /// <summary>
        /// Gets or Sets TrooperKillGoldShareFrac
        /// </summary>
        [JsonPropertyName("trooper_kill_gold_share_frac")]
        public List<decimal> TrooperKillGoldShareFrac { get; set; }

        /// <summary>
        /// Gets or Sets HeroKillGoldShareFrac
        /// </summary>
        [JsonPropertyName("hero_kill_gold_share_frac")]
        public List<decimal> HeroKillGoldShareFrac { get; set; }

        /// <summary>
        /// Gets or Sets AimSpringStrength
        /// </summary>
        [JsonPropertyName("aim_spring_strength")]
        public List<decimal> AimSpringStrength { get; set; }

        /// <summary>
        /// Gets or Sets TargetingSpringStrength
        /// </summary>
        [JsonPropertyName("targeting_spring_strength")]
        public List<decimal> TargetingSpringStrength { get; set; }

        /// <summary>
        /// Gets or Sets ObjectiveParams
        /// </summary>
        [JsonPropertyName("objective_params")]
        public ObjectiveParams ObjectiveParams { get; set; }

        /// <summary>
        /// Gets or Sets RejuvParams
        /// </summary>
        [JsonPropertyName("rejuv_params")]
        public RejuvParams RejuvParams { get; set; }

        /// <summary>
        /// Gets or Sets MiniMapOffsets
        /// </summary>
        [JsonPropertyName("mini_map_offsets")]
        public List<MiniMapOffsets> MiniMapOffsets { get; set; }

        /// <summary>
        /// Gets or Sets WeaponGroups
        /// </summary>
        [JsonPropertyName("weapon_groups")]
        public List<ItemGroup> WeaponGroups { get; set; }

        /// <summary>
        /// Gets or Sets ArmorGroups
        /// </summary>
        [JsonPropertyName("armor_groups")]
        public List<ItemGroup> ArmorGroups { get; set; }

        /// <summary>
        /// Gets or Sets SpiritGroups
        /// </summary>
        [JsonPropertyName("spirit_groups")]
        public List<ItemGroup> SpiritGroups { get; set; }

        /// <summary>
        /// Used to track the state of MinimapTeamRebelsColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ColorV1?> MinimapTeamRebelsColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets MinimapTeamRebelsColor
        /// </summary>
        [JsonPropertyName("minimap_team_rebels_color")]
        public ColorV1? MinimapTeamRebelsColor { get { return this.MinimapTeamRebelsColorOption; } set { this.MinimapTeamRebelsColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of MinimapTeamCombineColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ColorV1?> MinimapTeamCombineColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets MinimapTeamCombineColor
        /// </summary>
        [JsonPropertyName("minimap_team_combine_color")]
        public ColorV1? MinimapTeamCombineColor { get { return this.MinimapTeamCombineColorOption; } set { this.MinimapTeamCombineColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnemyObjectivesAndZiplineColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ColorV1?> EnemyObjectivesAndZiplineColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnemyObjectivesAndZiplineColor
        /// </summary>
        [JsonPropertyName("enemy_objectives_and_zipline_color")]
        public ColorV1? EnemyObjectivesAndZiplineColor { get { return this.EnemyObjectivesAndZiplineColorOption; } set { this.EnemyObjectivesAndZiplineColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnemyObjectivesColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ColorV1?> EnemyObjectivesColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnemyObjectivesColor
        /// </summary>
        [JsonPropertyName("enemy_objectives_color")]
        public ColorV1? EnemyObjectivesColor { get { return this.EnemyObjectivesColorOption; } set { this.EnemyObjectivesColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnemyZiplineColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ColorV1?> EnemyZiplineColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnemyZiplineColor
        /// </summary>
        [JsonPropertyName("enemy_zipline_color")]
        public ColorV1? EnemyZiplineColor { get { return this.EnemyZiplineColorOption; } set { this.EnemyZiplineColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of StreetBrawl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StreetBrawl?> StreetBrawlOption { get; private set; }

        /// <summary>
        /// Gets or Sets StreetBrawl
        /// </summary>
        [JsonPropertyName("street_brawl")]
        public StreetBrawl? StreetBrawl { get { return this.StreetBrawlOption; } set { this.StreetBrawlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenericDataV2 {\n");
            sb.Append("  DamageFlash: ").Append(DamageFlash).Append("\n");
            sb.Append("  GlitchSettings: ").Append(GlitchSettings).Append("\n");
            sb.Append("  LaneInfo: ").Append(LaneInfo).Append("\n");
            sb.Append("  NewPlayerMetrics: ").Append(NewPlayerMetrics).Append("\n");
            sb.Append("  ItemPricePerTier: ").Append(ItemPricePerTier).Append("\n");
            sb.Append("  TrooperKillGoldShareFrac: ").Append(TrooperKillGoldShareFrac).Append("\n");
            sb.Append("  HeroKillGoldShareFrac: ").Append(HeroKillGoldShareFrac).Append("\n");
            sb.Append("  AimSpringStrength: ").Append(AimSpringStrength).Append("\n");
            sb.Append("  TargetingSpringStrength: ").Append(TargetingSpringStrength).Append("\n");
            sb.Append("  ObjectiveParams: ").Append(ObjectiveParams).Append("\n");
            sb.Append("  RejuvParams: ").Append(RejuvParams).Append("\n");
            sb.Append("  MiniMapOffsets: ").Append(MiniMapOffsets).Append("\n");
            sb.Append("  WeaponGroups: ").Append(WeaponGroups).Append("\n");
            sb.Append("  ArmorGroups: ").Append(ArmorGroups).Append("\n");
            sb.Append("  SpiritGroups: ").Append(SpiritGroups).Append("\n");
            sb.Append("  MinimapTeamRebelsColor: ").Append(MinimapTeamRebelsColor).Append("\n");
            sb.Append("  MinimapTeamCombineColor: ").Append(MinimapTeamCombineColor).Append("\n");
            sb.Append("  EnemyObjectivesAndZiplineColor: ").Append(EnemyObjectivesAndZiplineColor).Append("\n");
            sb.Append("  EnemyObjectivesColor: ").Append(EnemyObjectivesColor).Append("\n");
            sb.Append("  EnemyZiplineColor: ").Append(EnemyZiplineColor).Append("\n");
            sb.Append("  StreetBrawl: ").Append(StreetBrawl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GenericDataV2" />
    /// </summary>
    public class GenericDataV2JsonConverter : JsonConverter<GenericDataV2>
    {
        /// <summary>
        /// Deserializes json to <see cref="GenericDataV2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GenericDataV2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DamageFlashV2?> damageFlash = default;
            Option<GlitchSettingsV2?> glitchSettings = default;
            Option<List<LaneInfoV2>?> laneInfo = default;
            Option<List<NewPlayerMetricsV2>?> newPlayerMetrics = default;
            Option<List<int>?> itemPricePerTier = default;
            Option<List<decimal>?> trooperKillGoldShareFrac = default;
            Option<List<decimal>?> heroKillGoldShareFrac = default;
            Option<List<decimal>?> aimSpringStrength = default;
            Option<List<decimal>?> targetingSpringStrength = default;
            Option<ObjectiveParams?> objectiveParams = default;
            Option<RejuvParams?> rejuvParams = default;
            Option<List<MiniMapOffsets>?> miniMapOffsets = default;
            Option<List<ItemGroup>?> weaponGroups = default;
            Option<List<ItemGroup>?> armorGroups = default;
            Option<List<ItemGroup>?> spiritGroups = default;
            Option<ColorV1?> minimapTeamRebelsColor = default;
            Option<ColorV1?> minimapTeamCombineColor = default;
            Option<ColorV1?> enemyObjectivesAndZiplineColor = default;
            Option<ColorV1?> enemyObjectivesColor = default;
            Option<ColorV1?> enemyZiplineColor = default;
            Option<StreetBrawl?> streetBrawl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "damage_flash":
                            damageFlash = new Option<DamageFlashV2?>(JsonSerializer.Deserialize<DamageFlashV2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "glitch_settings":
                            glitchSettings = new Option<GlitchSettingsV2?>(JsonSerializer.Deserialize<GlitchSettingsV2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "lane_info":
                            laneInfo = new Option<List<LaneInfoV2>?>(JsonSerializer.Deserialize<List<LaneInfoV2>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "new_player_metrics":
                            newPlayerMetrics = new Option<List<NewPlayerMetricsV2>?>(JsonSerializer.Deserialize<List<NewPlayerMetricsV2>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "item_price_per_tier":
                            itemPricePerTier = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "trooper_kill_gold_share_frac":
                            trooperKillGoldShareFrac = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "hero_kill_gold_share_frac":
                            heroKillGoldShareFrac = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "aim_spring_strength":
                            aimSpringStrength = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "targeting_spring_strength":
                            targetingSpringStrength = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "objective_params":
                            objectiveParams = new Option<ObjectiveParams?>(JsonSerializer.Deserialize<ObjectiveParams>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "rejuv_params":
                            rejuvParams = new Option<RejuvParams?>(JsonSerializer.Deserialize<RejuvParams>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "mini_map_offsets":
                            miniMapOffsets = new Option<List<MiniMapOffsets>?>(JsonSerializer.Deserialize<List<MiniMapOffsets>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "weapon_groups":
                            weaponGroups = new Option<List<ItemGroup>?>(JsonSerializer.Deserialize<List<ItemGroup>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "armor_groups":
                            armorGroups = new Option<List<ItemGroup>?>(JsonSerializer.Deserialize<List<ItemGroup>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "spirit_groups":
                            spiritGroups = new Option<List<ItemGroup>?>(JsonSerializer.Deserialize<List<ItemGroup>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "minimap_team_rebels_color":
                            minimapTeamRebelsColor = new Option<ColorV1?>(JsonSerializer.Deserialize<ColorV1>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "minimap_team_combine_color":
                            minimapTeamCombineColor = new Option<ColorV1?>(JsonSerializer.Deserialize<ColorV1>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "enemy_objectives_and_zipline_color":
                            enemyObjectivesAndZiplineColor = new Option<ColorV1?>(JsonSerializer.Deserialize<ColorV1>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "enemy_objectives_color":
                            enemyObjectivesColor = new Option<ColorV1?>(JsonSerializer.Deserialize<ColorV1>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "enemy_zipline_color":
                            enemyZiplineColor = new Option<ColorV1?>(JsonSerializer.Deserialize<ColorV1>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "street_brawl":
                            streetBrawl = new Option<StreetBrawl?>(JsonSerializer.Deserialize<StreetBrawl>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!damageFlash.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(damageFlash));

            if (!glitchSettings.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(glitchSettings));

            if (!laneInfo.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(laneInfo));

            if (!newPlayerMetrics.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(newPlayerMetrics));

            if (!itemPricePerTier.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(itemPricePerTier));

            if (!trooperKillGoldShareFrac.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(trooperKillGoldShareFrac));

            if (!heroKillGoldShareFrac.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(heroKillGoldShareFrac));

            if (!aimSpringStrength.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(aimSpringStrength));

            if (!targetingSpringStrength.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(targetingSpringStrength));

            if (!objectiveParams.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(objectiveParams));

            if (!rejuvParams.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(rejuvParams));

            if (!miniMapOffsets.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(miniMapOffsets));

            if (!weaponGroups.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(weaponGroups));

            if (!armorGroups.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(armorGroups));

            if (!spiritGroups.IsSet)
                throw new ArgumentException("Property is required for class GenericDataV2.", nameof(spiritGroups));

            if (damageFlash.IsSet && damageFlash.Value == null)
                throw new ArgumentNullException(nameof(damageFlash), "Property is not nullable for class GenericDataV2.");

            if (glitchSettings.IsSet && glitchSettings.Value == null)
                throw new ArgumentNullException(nameof(glitchSettings), "Property is not nullable for class GenericDataV2.");

            if (laneInfo.IsSet && laneInfo.Value == null)
                throw new ArgumentNullException(nameof(laneInfo), "Property is not nullable for class GenericDataV2.");

            if (newPlayerMetrics.IsSet && newPlayerMetrics.Value == null)
                throw new ArgumentNullException(nameof(newPlayerMetrics), "Property is not nullable for class GenericDataV2.");

            if (itemPricePerTier.IsSet && itemPricePerTier.Value == null)
                throw new ArgumentNullException(nameof(itemPricePerTier), "Property is not nullable for class GenericDataV2.");

            if (trooperKillGoldShareFrac.IsSet && trooperKillGoldShareFrac.Value == null)
                throw new ArgumentNullException(nameof(trooperKillGoldShareFrac), "Property is not nullable for class GenericDataV2.");

            if (heroKillGoldShareFrac.IsSet && heroKillGoldShareFrac.Value == null)
                throw new ArgumentNullException(nameof(heroKillGoldShareFrac), "Property is not nullable for class GenericDataV2.");

            if (aimSpringStrength.IsSet && aimSpringStrength.Value == null)
                throw new ArgumentNullException(nameof(aimSpringStrength), "Property is not nullable for class GenericDataV2.");

            if (targetingSpringStrength.IsSet && targetingSpringStrength.Value == null)
                throw new ArgumentNullException(nameof(targetingSpringStrength), "Property is not nullable for class GenericDataV2.");

            if (objectiveParams.IsSet && objectiveParams.Value == null)
                throw new ArgumentNullException(nameof(objectiveParams), "Property is not nullable for class GenericDataV2.");

            if (rejuvParams.IsSet && rejuvParams.Value == null)
                throw new ArgumentNullException(nameof(rejuvParams), "Property is not nullable for class GenericDataV2.");

            if (miniMapOffsets.IsSet && miniMapOffsets.Value == null)
                throw new ArgumentNullException(nameof(miniMapOffsets), "Property is not nullable for class GenericDataV2.");

            if (weaponGroups.IsSet && weaponGroups.Value == null)
                throw new ArgumentNullException(nameof(weaponGroups), "Property is not nullable for class GenericDataV2.");

            if (armorGroups.IsSet && armorGroups.Value == null)
                throw new ArgumentNullException(nameof(armorGroups), "Property is not nullable for class GenericDataV2.");

            if (spiritGroups.IsSet && spiritGroups.Value == null)
                throw new ArgumentNullException(nameof(spiritGroups), "Property is not nullable for class GenericDataV2.");

            return new GenericDataV2(damageFlash.Value!, glitchSettings.Value!, laneInfo.Value!, newPlayerMetrics.Value!, itemPricePerTier.Value!, trooperKillGoldShareFrac.Value!, heroKillGoldShareFrac.Value!, aimSpringStrength.Value!, targetingSpringStrength.Value!, objectiveParams.Value!, rejuvParams.Value!, miniMapOffsets.Value!, weaponGroups.Value!, armorGroups.Value!, spiritGroups.Value!, minimapTeamRebelsColor, minimapTeamCombineColor, enemyObjectivesAndZiplineColor, enemyObjectivesColor, enemyZiplineColor, streetBrawl);
        }

        /// <summary>
        /// Serializes a <see cref="GenericDataV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="genericDataV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GenericDataV2 genericDataV2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, genericDataV2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GenericDataV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="genericDataV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GenericDataV2 genericDataV2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (genericDataV2.DamageFlash == null)
                throw new ArgumentNullException(nameof(genericDataV2.DamageFlash), "Property is required for class GenericDataV2.");

            if (genericDataV2.GlitchSettings == null)
                throw new ArgumentNullException(nameof(genericDataV2.GlitchSettings), "Property is required for class GenericDataV2.");

            if (genericDataV2.LaneInfo == null)
                throw new ArgumentNullException(nameof(genericDataV2.LaneInfo), "Property is required for class GenericDataV2.");

            if (genericDataV2.NewPlayerMetrics == null)
                throw new ArgumentNullException(nameof(genericDataV2.NewPlayerMetrics), "Property is required for class GenericDataV2.");

            if (genericDataV2.ItemPricePerTier == null)
                throw new ArgumentNullException(nameof(genericDataV2.ItemPricePerTier), "Property is required for class GenericDataV2.");

            if (genericDataV2.TrooperKillGoldShareFrac == null)
                throw new ArgumentNullException(nameof(genericDataV2.TrooperKillGoldShareFrac), "Property is required for class GenericDataV2.");

            if (genericDataV2.HeroKillGoldShareFrac == null)
                throw new ArgumentNullException(nameof(genericDataV2.HeroKillGoldShareFrac), "Property is required for class GenericDataV2.");

            if (genericDataV2.AimSpringStrength == null)
                throw new ArgumentNullException(nameof(genericDataV2.AimSpringStrength), "Property is required for class GenericDataV2.");

            if (genericDataV2.TargetingSpringStrength == null)
                throw new ArgumentNullException(nameof(genericDataV2.TargetingSpringStrength), "Property is required for class GenericDataV2.");

            if (genericDataV2.ObjectiveParams == null)
                throw new ArgumentNullException(nameof(genericDataV2.ObjectiveParams), "Property is required for class GenericDataV2.");

            if (genericDataV2.RejuvParams == null)
                throw new ArgumentNullException(nameof(genericDataV2.RejuvParams), "Property is required for class GenericDataV2.");

            if (genericDataV2.MiniMapOffsets == null)
                throw new ArgumentNullException(nameof(genericDataV2.MiniMapOffsets), "Property is required for class GenericDataV2.");

            if (genericDataV2.WeaponGroups == null)
                throw new ArgumentNullException(nameof(genericDataV2.WeaponGroups), "Property is required for class GenericDataV2.");

            if (genericDataV2.ArmorGroups == null)
                throw new ArgumentNullException(nameof(genericDataV2.ArmorGroups), "Property is required for class GenericDataV2.");

            if (genericDataV2.SpiritGroups == null)
                throw new ArgumentNullException(nameof(genericDataV2.SpiritGroups), "Property is required for class GenericDataV2.");

            writer.WritePropertyName("damage_flash");
            JsonSerializer.Serialize(writer, genericDataV2.DamageFlash, jsonSerializerOptions);
            writer.WritePropertyName("glitch_settings");
            JsonSerializer.Serialize(writer, genericDataV2.GlitchSettings, jsonSerializerOptions);
            writer.WritePropertyName("lane_info");
            JsonSerializer.Serialize(writer, genericDataV2.LaneInfo, jsonSerializerOptions);
            writer.WritePropertyName("new_player_metrics");
            JsonSerializer.Serialize(writer, genericDataV2.NewPlayerMetrics, jsonSerializerOptions);
            writer.WritePropertyName("item_price_per_tier");
            JsonSerializer.Serialize(writer, genericDataV2.ItemPricePerTier, jsonSerializerOptions);
            writer.WritePropertyName("trooper_kill_gold_share_frac");
            JsonSerializer.Serialize(writer, genericDataV2.TrooperKillGoldShareFrac, jsonSerializerOptions);
            writer.WritePropertyName("hero_kill_gold_share_frac");
            JsonSerializer.Serialize(writer, genericDataV2.HeroKillGoldShareFrac, jsonSerializerOptions);
            writer.WritePropertyName("aim_spring_strength");
            JsonSerializer.Serialize(writer, genericDataV2.AimSpringStrength, jsonSerializerOptions);
            writer.WritePropertyName("targeting_spring_strength");
            JsonSerializer.Serialize(writer, genericDataV2.TargetingSpringStrength, jsonSerializerOptions);
            writer.WritePropertyName("objective_params");
            JsonSerializer.Serialize(writer, genericDataV2.ObjectiveParams, jsonSerializerOptions);
            writer.WritePropertyName("rejuv_params");
            JsonSerializer.Serialize(writer, genericDataV2.RejuvParams, jsonSerializerOptions);
            writer.WritePropertyName("mini_map_offsets");
            JsonSerializer.Serialize(writer, genericDataV2.MiniMapOffsets, jsonSerializerOptions);
            writer.WritePropertyName("weapon_groups");
            JsonSerializer.Serialize(writer, genericDataV2.WeaponGroups, jsonSerializerOptions);
            writer.WritePropertyName("armor_groups");
            JsonSerializer.Serialize(writer, genericDataV2.ArmorGroups, jsonSerializerOptions);
            writer.WritePropertyName("spirit_groups");
            JsonSerializer.Serialize(writer, genericDataV2.SpiritGroups, jsonSerializerOptions);
            if (genericDataV2.MinimapTeamRebelsColorOption.IsSet)
                if (genericDataV2.MinimapTeamRebelsColorOption.Value != null)
                {
                    writer.WritePropertyName("minimap_team_rebels_color");
                    JsonSerializer.Serialize(writer, genericDataV2.MinimapTeamRebelsColor, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("minimap_team_rebels_color");
            if (genericDataV2.MinimapTeamCombineColorOption.IsSet)
                if (genericDataV2.MinimapTeamCombineColorOption.Value != null)
                {
                    writer.WritePropertyName("minimap_team_combine_color");
                    JsonSerializer.Serialize(writer, genericDataV2.MinimapTeamCombineColor, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("minimap_team_combine_color");
            if (genericDataV2.EnemyObjectivesAndZiplineColorOption.IsSet)
                if (genericDataV2.EnemyObjectivesAndZiplineColorOption.Value != null)
                {
                    writer.WritePropertyName("enemy_objectives_and_zipline_color");
                    JsonSerializer.Serialize(writer, genericDataV2.EnemyObjectivesAndZiplineColor, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("enemy_objectives_and_zipline_color");
            if (genericDataV2.EnemyObjectivesColorOption.IsSet)
                if (genericDataV2.EnemyObjectivesColorOption.Value != null)
                {
                    writer.WritePropertyName("enemy_objectives_color");
                    JsonSerializer.Serialize(writer, genericDataV2.EnemyObjectivesColor, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("enemy_objectives_color");
            if (genericDataV2.EnemyZiplineColorOption.IsSet)
                if (genericDataV2.EnemyZiplineColorOption.Value != null)
                {
                    writer.WritePropertyName("enemy_zipline_color");
                    JsonSerializer.Serialize(writer, genericDataV2.EnemyZiplineColor, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("enemy_zipline_color");
            if (genericDataV2.StreetBrawlOption.IsSet)
                if (genericDataV2.StreetBrawlOption.Value != null)
                {
                    writer.WritePropertyName("street_brawl");
                    JsonSerializer.Serialize(writer, genericDataV2.StreetBrawl, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("street_brawl");
        }
    }
}
