// <auto-generated>
/*
 * Assets - Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AssetsDeadlockApiClient.Client;

namespace AssetsDeadlockApiClient.Model
{
    /// <summary>
    /// HeroShopStatDisplayV2
    /// </summary>
    public partial class HeroShopStatDisplayV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeroShopStatDisplayV2" /> class.
        /// </summary>
        /// <param name="spiritStatsDisplay">spiritStatsDisplay</param>
        /// <param name="vitalityStatsDisplay">vitalityStatsDisplay</param>
        /// <param name="weaponStatsDisplay">weaponStatsDisplay</param>
        [JsonConstructor]
        public HeroShopStatDisplayV2(RawHeroShopSpiritStatsDisplayV2 spiritStatsDisplay, RawHeroShopVitalityStatsDisplayV2 vitalityStatsDisplay, HeroShopWeaponStatsDisplayV2 weaponStatsDisplay)
        {
            SpiritStatsDisplay = spiritStatsDisplay;
            VitalityStatsDisplay = vitalityStatsDisplay;
            WeaponStatsDisplay = weaponStatsDisplay;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SpiritStatsDisplay
        /// </summary>
        [JsonPropertyName("spirit_stats_display")]
        public RawHeroShopSpiritStatsDisplayV2 SpiritStatsDisplay { get; set; }

        /// <summary>
        /// Gets or Sets VitalityStatsDisplay
        /// </summary>
        [JsonPropertyName("vitality_stats_display")]
        public RawHeroShopVitalityStatsDisplayV2 VitalityStatsDisplay { get; set; }

        /// <summary>
        /// Gets or Sets WeaponStatsDisplay
        /// </summary>
        [JsonPropertyName("weapon_stats_display")]
        public HeroShopWeaponStatsDisplayV2 WeaponStatsDisplay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeroShopStatDisplayV2 {\n");
            sb.Append("  SpiritStatsDisplay: ").Append(SpiritStatsDisplay).Append("\n");
            sb.Append("  VitalityStatsDisplay: ").Append(VitalityStatsDisplay).Append("\n");
            sb.Append("  WeaponStatsDisplay: ").Append(WeaponStatsDisplay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HeroShopStatDisplayV2" />
    /// </summary>
    public class HeroShopStatDisplayV2JsonConverter : JsonConverter<HeroShopStatDisplayV2>
    {
        /// <summary>
        /// Deserializes json to <see cref="HeroShopStatDisplayV2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HeroShopStatDisplayV2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<RawHeroShopSpiritStatsDisplayV2?> spiritStatsDisplay = default;
            Option<RawHeroShopVitalityStatsDisplayV2?> vitalityStatsDisplay = default;
            Option<HeroShopWeaponStatsDisplayV2?> weaponStatsDisplay = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "spirit_stats_display":
                            spiritStatsDisplay = new Option<RawHeroShopSpiritStatsDisplayV2?>(JsonSerializer.Deserialize<RawHeroShopSpiritStatsDisplayV2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "vitality_stats_display":
                            vitalityStatsDisplay = new Option<RawHeroShopVitalityStatsDisplayV2?>(JsonSerializer.Deserialize<RawHeroShopVitalityStatsDisplayV2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "weapon_stats_display":
                            weaponStatsDisplay = new Option<HeroShopWeaponStatsDisplayV2?>(JsonSerializer.Deserialize<HeroShopWeaponStatsDisplayV2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!spiritStatsDisplay.IsSet)
                throw new ArgumentException("Property is required for class HeroShopStatDisplayV2.", nameof(spiritStatsDisplay));

            if (!vitalityStatsDisplay.IsSet)
                throw new ArgumentException("Property is required for class HeroShopStatDisplayV2.", nameof(vitalityStatsDisplay));

            if (!weaponStatsDisplay.IsSet)
                throw new ArgumentException("Property is required for class HeroShopStatDisplayV2.", nameof(weaponStatsDisplay));

            if (spiritStatsDisplay.IsSet && spiritStatsDisplay.Value == null)
                throw new ArgumentNullException(nameof(spiritStatsDisplay), "Property is not nullable for class HeroShopStatDisplayV2.");

            if (vitalityStatsDisplay.IsSet && vitalityStatsDisplay.Value == null)
                throw new ArgumentNullException(nameof(vitalityStatsDisplay), "Property is not nullable for class HeroShopStatDisplayV2.");

            if (weaponStatsDisplay.IsSet && weaponStatsDisplay.Value == null)
                throw new ArgumentNullException(nameof(weaponStatsDisplay), "Property is not nullable for class HeroShopStatDisplayV2.");

            return new HeroShopStatDisplayV2(spiritStatsDisplay.Value!, vitalityStatsDisplay.Value!, weaponStatsDisplay.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="HeroShopStatDisplayV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heroShopStatDisplayV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HeroShopStatDisplayV2 heroShopStatDisplayV2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, heroShopStatDisplayV2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HeroShopStatDisplayV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heroShopStatDisplayV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HeroShopStatDisplayV2 heroShopStatDisplayV2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (heroShopStatDisplayV2.SpiritStatsDisplay == null)
                throw new ArgumentNullException(nameof(heroShopStatDisplayV2.SpiritStatsDisplay), "Property is required for class HeroShopStatDisplayV2.");

            if (heroShopStatDisplayV2.VitalityStatsDisplay == null)
                throw new ArgumentNullException(nameof(heroShopStatDisplayV2.VitalityStatsDisplay), "Property is required for class HeroShopStatDisplayV2.");

            if (heroShopStatDisplayV2.WeaponStatsDisplay == null)
                throw new ArgumentNullException(nameof(heroShopStatDisplayV2.WeaponStatsDisplay), "Property is required for class HeroShopStatDisplayV2.");

            writer.WritePropertyName("spirit_stats_display");
            JsonSerializer.Serialize(writer, heroShopStatDisplayV2.SpiritStatsDisplay, jsonSerializerOptions);
            writer.WritePropertyName("vitality_stats_display");
            JsonSerializer.Serialize(writer, heroShopStatDisplayV2.VitalityStatsDisplay, jsonSerializerOptions);
            writer.WritePropertyName("weapon_stats_display");
            JsonSerializer.Serialize(writer, heroShopStatDisplayV2.WeaponStatsDisplay, jsonSerializerOptions);
        }
    }
}
