// <auto-generated>
/*
 * Assets - Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AssetsDeadlockApiClient.Client;

namespace AssetsDeadlockApiClient.Model
{
    /// <summary>
    /// RawAbilityUpgradePropertyUpgradeV2
    /// </summary>
    public partial class RawAbilityUpgradePropertyUpgradeV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RawAbilityUpgradePropertyUpgradeV2" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="bonus">bonus</param>
        /// <param name="scaleStatFilter">scaleStatFilter</param>
        /// <param name="upgradeType">upgradeType</param>
        [JsonConstructor]
        public RawAbilityUpgradePropertyUpgradeV2(string name, Bonus bonus, Option<string?> scaleStatFilter = default, Option<string?> upgradeType = default)
        {
            Name = name;
            Bonus = bonus;
            ScaleStatFilterOption = scaleStatFilter;
            UpgradeTypeOption = upgradeType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Bonus
        /// </summary>
        [JsonPropertyName("bonus")]
        public Bonus Bonus { get; set; }

        /// <summary>
        /// Used to track the state of ScaleStatFilter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ScaleStatFilterOption { get; private set; }

        /// <summary>
        /// Gets or Sets ScaleStatFilter
        /// </summary>
        [JsonPropertyName("scale_stat_filter")]
        public string? ScaleStatFilter { get { return this.ScaleStatFilterOption; } set { this.ScaleStatFilterOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpgradeType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpgradeTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpgradeType
        /// </summary>
        [JsonPropertyName("upgrade_type")]
        public string? UpgradeType { get { return this.UpgradeTypeOption; } set { this.UpgradeTypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RawAbilityUpgradePropertyUpgradeV2 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Bonus: ").Append(Bonus).Append("\n");
            sb.Append("  ScaleStatFilter: ").Append(ScaleStatFilter).Append("\n");
            sb.Append("  UpgradeType: ").Append(UpgradeType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RawAbilityUpgradePropertyUpgradeV2" />
    /// </summary>
    public class RawAbilityUpgradePropertyUpgradeV2JsonConverter : JsonConverter<RawAbilityUpgradePropertyUpgradeV2>
    {
        /// <summary>
        /// Deserializes json to <see cref="RawAbilityUpgradePropertyUpgradeV2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RawAbilityUpgradePropertyUpgradeV2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<Bonus?> bonus = default;
            Option<string?> scaleStatFilter = default;
            Option<string?> upgradeType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "bonus":
                            bonus = new Option<Bonus?>(JsonSerializer.Deserialize<Bonus>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scale_stat_filter":
                            scaleStatFilter = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "upgrade_type":
                            upgradeType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class RawAbilityUpgradePropertyUpgradeV2.", nameof(name));

            if (!bonus.IsSet)
                throw new ArgumentException("Property is required for class RawAbilityUpgradePropertyUpgradeV2.", nameof(bonus));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class RawAbilityUpgradePropertyUpgradeV2.");

            if (bonus.IsSet && bonus.Value == null)
                throw new ArgumentNullException(nameof(bonus), "Property is not nullable for class RawAbilityUpgradePropertyUpgradeV2.");

            return new RawAbilityUpgradePropertyUpgradeV2(name.Value!, bonus.Value!, scaleStatFilter, upgradeType);
        }

        /// <summary>
        /// Serializes a <see cref="RawAbilityUpgradePropertyUpgradeV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rawAbilityUpgradePropertyUpgradeV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RawAbilityUpgradePropertyUpgradeV2 rawAbilityUpgradePropertyUpgradeV2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rawAbilityUpgradePropertyUpgradeV2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RawAbilityUpgradePropertyUpgradeV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rawAbilityUpgradePropertyUpgradeV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RawAbilityUpgradePropertyUpgradeV2 rawAbilityUpgradePropertyUpgradeV2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rawAbilityUpgradePropertyUpgradeV2.Name == null)
                throw new ArgumentNullException(nameof(rawAbilityUpgradePropertyUpgradeV2.Name), "Property is required for class RawAbilityUpgradePropertyUpgradeV2.");

            if (rawAbilityUpgradePropertyUpgradeV2.Bonus == null)
                throw new ArgumentNullException(nameof(rawAbilityUpgradePropertyUpgradeV2.Bonus), "Property is required for class RawAbilityUpgradePropertyUpgradeV2.");

            writer.WriteString("name", rawAbilityUpgradePropertyUpgradeV2.Name);

            writer.WritePropertyName("bonus");
            JsonSerializer.Serialize(writer, rawAbilityUpgradePropertyUpgradeV2.Bonus, jsonSerializerOptions);
            if (rawAbilityUpgradePropertyUpgradeV2.ScaleStatFilterOption.IsSet)
                if (rawAbilityUpgradePropertyUpgradeV2.ScaleStatFilterOption.Value != null)
                    writer.WriteString("scale_stat_filter", rawAbilityUpgradePropertyUpgradeV2.ScaleStatFilter);
                else
                    writer.WriteNull("scale_stat_filter");

            if (rawAbilityUpgradePropertyUpgradeV2.UpgradeTypeOption.IsSet)
                if (rawAbilityUpgradePropertyUpgradeV2.UpgradeTypeOption.Value != null)
                    writer.WriteString("upgrade_type", rawAbilityUpgradePropertyUpgradeV2.UpgradeType);
                else
                    writer.WriteNull("upgrade_type");
        }
    }
}
