/* tslint:disable */
/* eslint-disable */
/**
 * Assets - Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AimingShotSpreadPenalty } from './aiming-shot-spread-penalty.js';
// May contain unused imports in some cases
// @ts-ignore
import type { RawItemWeaponInfoBulletSpeedCurveV2 } from './raw-item-weapon-info-bullet-speed-curve-v2.js';
// May contain unused imports in some cases
// @ts-ignore
import type { RawWeaponInfoHorizontalRecoilV2 } from './raw-weapon-info-horizontal-recoil-v2.js';
// May contain unused imports in some cases
// @ts-ignore
import type { RawWeaponInfoVerticalRecoilV2 } from './raw-weapon-info-vertical-recoil-v2.js';
// May contain unused imports in some cases
// @ts-ignore
import type { StandingShotSpreadPenalty } from './standing-shot-spread-penalty.js';

export interface WeaponInfoV2 {
    'can_zoom'?: boolean | null;
    'bullet_damage'?: number | null;
    'bullet_gravity_scale'?: number | null;
    'bullet_inherit_shooter_velocity_scale'?: number | null;
    'bullet_lifetime'?: number | null;
    'bullet_radius'?: number | null;
    'bullet_radius_vs_world'?: number | null;
    'bullet_reflect_amount'?: number | null;
    'bullet_reflect_scale'?: number | null;
    'bullet_whiz_distance'?: number | null;
    'burst_shot_cooldown'?: number | null;
    'crit_bonus_against_npcs'?: number | null;
    'crit_bonus_end'?: number | null;
    'crit_bonus_end_range'?: number | null;
    'crit_bonus_start'?: number | null;
    'crit_bonus_start_range'?: number | null;
    'cycle_time'?: number | null;
    'spins_up'?: boolean | null;
    'is_semi_auto'?: boolean | null;
    'semi_auto_cycle_rate'?: number | null;
    'max_spin_cycle_time'?: number | null;
    'spin_increase_rate'?: number | null;
    'spin_decay_rate'?: number | null;
    'build_up_rate'?: number | null;
    'intra_burst_cycle_time'?: number | null;
    'damage_falloff_bias'?: number | null;
    'damage_falloff_end_range'?: number | null;
    'damage_falloff_end_scale'?: number | null;
    'damage_falloff_start_range'?: number | null;
    'damage_falloff_start_scale'?: number | null;
    'horizontal_punch'?: number | null;
    'range'?: number | null;
    'recoil_recovery_delay_factor'?: number | null;
    'bullet_speed'?: number | null;
    'recoil_recovery_speed'?: number | null;
    'recoil_shot_index_recovery_time_factor'?: number | null;
    'recoil_speed'?: number | null;
    'reload_move_speed'?: number | null;
    'scatter_yaw_scale'?: number | null;
    'aiming_shot_spread_penalty'?: AimingShotSpreadPenalty | null;
    'standing_shot_spread_penalty'?: StandingShotSpreadPenalty | null;
    'shoot_move_speed_percent'?: number | null;
    'shoot_spread_penalty_decay'?: number | null;
    'shoot_spread_penalty_decay_delay'?: number | null;
    'shoot_spread_penalty_per_shot'?: number | null;
    'shooting_up_spread_penalty'?: number | null;
    'vertical_punch'?: number | null;
    'zoom_fov'?: number | null;
    'zoom_move_speed_percent'?: number | null;
    'bullets'?: number | null;
    'reload_single_bullets_initial_delay'?: number | null;
    'reload_single_bullets'?: boolean | null;
    'reload_single_bullets_allow_cancel'?: boolean | null;
    'burst_shot_count'?: number | null;
    'clip_size'?: number | null;
    'spread'?: number | null;
    'standing_spread'?: number | null;
    'low_ammo_indicator_threshold'?: number | null;
    'recoil_seed'?: number | null;
    'reload_duration'?: number | null;
    'bullet_speed_curve'?: RawItemWeaponInfoBulletSpeedCurveV2 | null;
    'horizontal_recoil'?: RawWeaponInfoHorizontalRecoilV2 | null;
    'vertical_recoil'?: RawWeaponInfoVerticalRecoilV2 | null;
    /**
     * Calculates the shots per second of the weapon
     */
    'shots_per_second': number | null;
    /**
     * Calculates the shots per second of the weapon adjusted for reload time
     */
    'shots_per_second_with_reload': number | null;
    /**
     * Calculates the bullets per second of the weapon, by multiplying shots per second by bullets per shot.
     */
    'bullets_per_second': number | null;
    /**
     * Calculates the bullets per second of the weapon adjusted for reload time.
     */
    'bullets_per_second_with_reload': number | null;
    /**
     * Calculates the damage per second of the weapon, by multiplying bullets per second by bullet damage.
     */
    'damage_per_second': number | null;
    /**
     * Calculates the damage per second of the weapon adjusted for reload time.
     */
    'damage_per_second_with_reload': number | null;
    /**
     * Calculates the damage per shot of the weapon, by multiplying bullets per shot by bullet damage.
     */
    'damage_per_shot': number | null;
    /**
     * Calculates the damage per magazine of the weapon, by multiplying clip size by damage per shot.
     */
    'damage_per_magazine': number | null;
}

