/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetItemsByHeroIdV2ItemsByHeroIdIdGetQueryResponse, GetItemsByHeroIdV2ItemsByHeroIdIdGetPathParams, GetItemsByHeroIdV2ItemsByHeroIdIdGetQueryParams, GetItemsByHeroIdV2ItemsByHeroIdIdGet422 } from "../types/GetItemsByHeroIdV2ItemsByHeroIdIdGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetItemsByHeroIdV2ItemsByHeroIdIdGetUrl(id: GetItemsByHeroIdV2ItemsByHeroIdIdGetPathParams["id"]) {
  const res = { method: 'GET', url: `/v2/items/by-hero-id/${id}` as const }
return res
}

/**
 * @summary Get Items By Hero Id
 * {@link /v2/items/by-hero-id/:id}
 */
export async function getItemsByHeroIdV2ItemsByHeroIdIdGet(id: GetItemsByHeroIdV2ItemsByHeroIdIdGetPathParams["id"], params?: GetItemsByHeroIdV2ItemsByHeroIdIdGetQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client:request = fetch, ...requestConfig } = config


const res = await request<GetItemsByHeroIdV2ItemsByHeroIdIdGetQueryResponse, ResponseErrorConfig<GetItemsByHeroIdV2ItemsByHeroIdIdGet422>, unknown>({ method : "GET", url : getGetItemsByHeroIdV2ItemsByHeroIdIdGetUrl(id).url.toString(), params, ... requestConfig })
return res.data
}