## InternalApi

### Add Prioritized Steam Account
## Add Prioritized Steam Account
POST https://api.deadlock-api.com/v1/patron/steam-accounts?api_key={{queryKey}}
Content-Type: application/json
Accept: application/json
X-API-KEY: {{apiKey}}

{
 "steam_id3": "<number>"
}


### Remove Prioritized Steam Account
## Remove Prioritized Steam Account
DELETE https://api.deadlock-api.com/v1/patron/steam-accounts/{{account_id}}?api_key={{queryKey}}
Accept: application/json
X-API-KEY: {{apiKey}}

### Match Salts Ingest
## Match Salts Ingest
POST https://api.deadlock-api.com/v1/matches/salts
Content-Type: application/json

{
 
}


### List Prioritized Steam Accounts
## List Prioritized Steam Accounts
GET https://api.deadlock-api.com/v1/patron/steam-accounts?api_key={{queryKey}}
Accept: application/json
X-API-KEY: {{apiKey}}

### Reactivate Prioritized Steam Account
## Reactivate Prioritized Steam Account
POST https://api.deadlock-api.com/v1/patron/steam-accounts/{{account_id}}/reactivate?api_key={{queryKey}}
Accept: application/json
X-API-KEY: {{apiKey}}

### Replace Prioritized Steam Account
## Replace Prioritized Steam Account
PUT https://api.deadlock-api.com/v1/patron/steam-accounts/{{account_id}}?api_key={{queryKey}}
Content-Type: application/json
Accept: application/json
X-API-KEY: {{apiKey}}

{
 "steam_id3": "<number>"
}


### Submit Website Feedback
## Submit Website Feedback
POST https://api.deadlock-api.com/v1/feedback
Content-Type: application/json

{
 "build_id": "<string>",
 "comment": "<string>",
 "element_text": "<string>",
 "kind": "<string>",
 "nickname": "<string>",
 "page_url": "<string>",
 "selector": "<string>",
 "source": "<string>",
 "targets": "<string>",
 "viewport": "<string>"
}

