## DataPrivacyApi

### Request Data Deletion
## Request Data Deletion
POST https://api.deadlock-api.com/v1/data-privacy/request-deletion
Content-Type: application/json
Accept: text/plain

{
 "open_id_params": "<string>",
 "steam_id": "<number>"
}


### Request Data Tracking
## Request Data Tracking
POST https://api.deadlock-api.com/v1/data-privacy/request-tracking
Content-Type: application/json
Accept: text/plain

{
 "open_id_params": "<string>",
 "steam_id": "<number>"
}

