## ESportsApi

### Ingest
## Ingest
POST https://api.deadlock-api.com/v1/esports/ingest/match
Content-Type: application/json

{
 "match_id": "<number>",
 "provider": "<string>",
 "scheduled_date": "<string>",
 "status": "<string>",
 "team0_name": "<string>",
 "team1_name": "<string>",
 "tournament_name": "<string>",
 "tournament_stage": "<string>",
 "update_id": "<string>"
}


### List Matches
## List Matches
GET https://api.deadlock-api.com/v1/esports/matches
Accept: application/json
