## MatchesApi

### Active
## Active
GET https://api.deadlock-api.com/v1/matches/active?accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Active as Protobuf
## Active as Protobuf
GET https://api.deadlock-api.com/v1/matches/active/raw
Accept: application/octet-stream

### Bulk Metadata
## Bulk Metadata
GET https://api.deadlock-api.com/v1/matches/metadata?includeInfo={{includeInfo}}&includeMoreInfo={{includeMoreInfo}}&includeObjectives={{includeObjectives}}&includeMidBoss={{includeMidBoss}}&includePlayerInfo={{includePlayerInfo}}&includePlayerItems={{includePlayerItems}}&includePlayerStats={{includePlayerStats}}&includePlayerDeathDetails={{includePlayerDeathDetails}}&gameMode={{gameMode}}&matchIds={{matchIds}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&isHighSkillRangeParties={{isHighSkillRangeParties}}&isLowPriPool={{isLowPriPool}}&isNewPlayerPool={{isNewPlayerPool}}&accountIds={{accountIds}}&heroIds={{heroIds}}&orderBy={{orderBy}}&orderDirection={{orderDirection}}&limit={{limit}}
Accept: application/octet-stream

### Metadata
## Metadata
GET https://api.deadlock-api.com/v1/matches/{{match_id}}/metadata?isCustom={{isCustom}}

### Metadata as Protobuf
## Metadata as Protobuf
GET https://api.deadlock-api.com/v1/matches/{{match_id}}/metadata/raw?isCustom={{isCustom}}
Accept: application/octet-stream

### Recently Fetched
## Recently Fetched
GET https://api.deadlock-api.com/v1/matches/recently-fetched?playerIngestedOnly={{playerIngestedOnly}}
Accept: application/json

### Salts
## Salts
GET https://api.deadlock-api.com/v1/matches/{{match_id}}/salts
Accept: application/json

### Live Broadcast URL
## Live Broadcast URL
GET https://api.deadlock-api.com/v1/matches/{{match_id}}/live/url
Accept: application/json
