## ServersApi

### Game Server Metric Ingest
## Game Server Metric Ingest
POST https://api.deadlock-api.com/v1/servers/metrics
Content-Type: application/json

{
 "account_id": "<number>",
 "game_mode": "<string>",
 "game_mode_version": "<string>",
 "map": "<string>",
 "metadata": "<string>",
 "metric_name": "<string>",
 "metric_value": "<number>",
 "region": "<string>",
 "server_id": "<string>"
}


### List Game Servers
## List Game Servers
GET https://api.deadlock-api.com/v1/servers
Accept: application/json

### Game Server Status
## Game Server Status
POST https://api.deadlock-api.com/v1/servers/status
Content-Type: application/json
Accept: application/json

{
 "current_player_count": "<number>",
 "game_mode": "<string>",
 "ip": "<string>",
 "port": "<number>",
 "region": "<string>",
 "server_id": "<string>"
}

