// tslint:disable
/**
 * Assets - Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectiveParams
 */
export interface ObjectiveParams  {
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    goldPerOrb: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    nearPlayerSplitPct: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    tier1GoldKill: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    tier1GoldOrbs: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    tier2GoldKill: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    tier2GoldOrbs: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    baseGuardiansGoldKill: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    baseGuardiansGoldOrbs: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    shrinesGoldKill: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    shrinesGoldOrbs: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    patronPhase1GoldKill: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveParams
     */
    patronPhase1GoldOrbs: number;
}

export function ObjectiveParamsFromJSON(json: any): ObjectiveParams {
    return {
        'goldPerOrb': json['gold_per_orb'],
        'nearPlayerSplitPct': json['near_player_split_pct'],
        'tier1GoldKill': json['tier1_gold_kill'],
        'tier1GoldOrbs': json['tier1_gold_orbs'],
        'tier2GoldKill': json['tier2_gold_kill'],
        'tier2GoldOrbs': json['tier2_gold_orbs'],
        'baseGuardiansGoldKill': json['base_guardians_gold_kill'],
        'baseGuardiansGoldOrbs': json['base_guardians_gold_orbs'],
        'shrinesGoldKill': json['shrines_gold_kill'],
        'shrinesGoldOrbs': json['shrines_gold_orbs'],
        'patronPhase1GoldKill': json['patron_phase1_gold_kill'],
        'patronPhase1GoldOrbs': json['patron_phase1_gold_orbs'],
    };
}

export function ObjectiveParamsToJSON(value?: ObjectiveParams): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'gold_per_orb': value.goldPerOrb,
        'near_player_split_pct': value.nearPlayerSplitPct,
        'tier1_gold_kill': value.tier1GoldKill,
        'tier1_gold_orbs': value.tier1GoldOrbs,
        'tier2_gold_kill': value.tier2GoldKill,
        'tier2_gold_orbs': value.tier2GoldOrbs,
        'base_guardians_gold_kill': value.baseGuardiansGoldKill,
        'base_guardians_gold_orbs': value.baseGuardiansGoldOrbs,
        'shrines_gold_kill': value.shrinesGoldKill,
        'shrines_gold_orbs': value.shrinesGoldOrbs,
        'patron_phase1_gold_kill': value.patronPhase1GoldKill,
        'patron_phase1_gold_orbs': value.patronPhase1GoldOrbs,
    };
}


