/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { GetIconsV1IconsGetQueryResponse, GetIconsV1IconsGetQueryParams, GetIconsV1IconsGet422 } from '../types/GetIconsV1IconsGet.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'

function getGetIconsV1IconsGetUrl() {
  const res = { method: 'GET', url: `/v1/icons` as const }
  return res
}

/**
 * @summary Get Icons
 * {@link /v1/icons}
 */
export async function getIconsV1IconsGet(params?: GetIconsV1IconsGetQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetIconsV1IconsGetQueryResponse, ResponseErrorConfig<GetIconsV1IconsGet422>, unknown>({
    method: 'GET',
    url: getGetIconsV1IconsGetUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}