/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package deadlock_api_client.models

import deadlock_api_client.models.Ability
import deadlock_api_client.models.AbilityActivation
import deadlock_api_client.models.AbilityImbue
import deadlock_api_client.models.AbilityTooltipDetails
import deadlock_api_client.models.AbilityType
import deadlock_api_client.models.AbilityVideos
import deadlock_api_client.models.DependantAbilities
import deadlock_api_client.models.ItemSlotType
import deadlock_api_client.models.ItemType
import deadlock_api_client.models.RawAbilityUpgrade
import deadlock_api_client.models.RawCustomCrosshairSettings
import deadlock_api_client.models.RawItemWeaponInfoInner
import deadlock_api_client.models.Upgrade
import deadlock_api_client.models.UpgradeDescription
import deadlock_api_client.models.UpgradeProperty
import deadlock_api_client.models.UpgradeTooltipSection
import deadlock_api_client.models.Weapon

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param className 
 * @param description 
 * @param id 
 * @param name 
 * @param type 
 * @param activation 
 * @param isActiveItem 
 * @param itemSlotType 
 * @param itemTier 
 * @param shopable 
 * @param abilityType 
 * @param behaviours 
 * @param bossDamageScale 
 * @param dependantAbilities 
 * @param dependentAbilities 
 * @param grantAmmoOnCast 
 * @param hero 
 * @param heroes 
 * @param image 
 * @param imageWebp 
 * @param properties 
 * @param startTrained 
 * @param tooltipDetails 
 * @param updateTime 
 * @param upgrades 
 * @param videos 
 * @param weaponInfo 
 * @param crosshairCssClass 
 * @param customCrosshairSettings 
 * @param useCustomCrosshairSettings 
 * @param componentItems 
 * @param cost 
 * @param disabled 
 * @param imbue 
 * @param shopImage 
 * @param shopImageSmall 
 * @param shopImageSmallWebp 
 * @param shopImageWebp 
 * @param tooltipSections 
 */


data class Item (

    @Json(name = "class_name")
    val className: kotlin.String,

    @Json(name = "description")
    val description: UpgradeDescription,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "type")
    val type: ItemType,

    @Json(name = "activation")
    val activation: AbilityActivation,

    @Json(name = "is_active_item")
    val isActiveItem: kotlin.Boolean,

    @Json(name = "item_slot_type")
    val itemSlotType: ItemSlotType,

    @Json(name = "item_tier")
    val itemTier: kotlin.Int,

    @Json(name = "shopable")
    val shopable: kotlin.Boolean,

    @Json(name = "ability_type")
    val abilityType: AbilityType? = null,

    @Json(name = "behaviours")
    val behaviours: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "boss_damage_scale")
    val bossDamageScale: kotlin.Double? = null,

    @Json(name = "dependant_abilities")
    val dependantAbilities: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "dependent_abilities")
    val dependentAbilities: kotlin.collections.Map<kotlin.String, DependantAbilities>? = null,

    @Json(name = "grant_ammo_on_cast")
    val grantAmmoOnCast: kotlin.Boolean? = null,

    @Json(name = "hero")
    val hero: kotlin.Int? = null,

    @Json(name = "heroes")
    val heroes: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "image_webp")
    val imageWebp: kotlin.String? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, UpgradeProperty>? = null,

    @Json(name = "start_trained")
    val startTrained: kotlin.Boolean? = null,

    @Json(name = "tooltip_details")
    val tooltipDetails: AbilityTooltipDetails? = null,

    @Json(name = "update_time")
    val updateTime: kotlin.Long? = null,

    @Json(name = "upgrades")
    val upgrades: kotlin.collections.List<RawAbilityUpgrade>? = null,

    @Json(name = "videos")
    val videos: AbilityVideos? = null,

    @Json(name = "weapon_info")
    val weaponInfo: RawItemWeaponInfoInner? = null,

    @Json(name = "crosshair_css_class")
    val crosshairCssClass: kotlin.String? = null,

    @Json(name = "custom_crosshair_settings")
    val customCrosshairSettings: RawCustomCrosshairSettings? = null,

    @Json(name = "use_custom_crosshair_settings")
    val useCustomCrosshairSettings: kotlin.Boolean? = null,

    @Json(name = "component_items")
    val componentItems: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "cost")
    val cost: kotlin.Int? = null,

    @Json(name = "disabled")
    val disabled: kotlin.Boolean? = null,

    @Json(name = "imbue")
    val imbue: AbilityImbue? = null,

    @Json(name = "shop_image")
    val shopImage: kotlin.String? = null,

    @Json(name = "shop_image_small")
    val shopImageSmall: kotlin.String? = null,

    @Json(name = "shop_image_small_webp")
    val shopImageSmallWebp: kotlin.String? = null,

    @Json(name = "shop_image_webp")
    val shopImageWebp: kotlin.String? = null,

    @Json(name = "tooltip_sections")
    val tooltipSections: kotlin.collections.List<UpgradeTooltipSection>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

