/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package deadlock_api_client.models

import deadlock_api_client.models.MapImages
import deadlock_api_client.models.ObjectivePosition
import deadlock_api_client.models.ZiplanePath

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * The `/v1/assets/map` response.
 *
 * @param images 
 * @param objectivePositions 
 * @param radius 
 * @param ziplinePaths 
 */


data class MapData (

    @Json(name = "images")
    val images: MapImages,

    @Json(name = "objective_positions")
    val objectivePositions: kotlin.collections.Map<kotlin.String, ObjectivePosition>,

    @Json(name = "radius")
    val radius: kotlin.Int,

    @Json(name = "zipline_paths")
    val ziplinePaths: kotlin.collections.List<ZiplanePath>

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

