/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package deadlock_api_client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * Fixed CDN URLs for the minimap image layers.
 *
 * @param background 
 * @param frame 
 * @param mid 
 * @param minimap 
 * @param plain 
 */


data class MapImages (

    @Json(name = "background")
    val background: kotlin.String,

    @Json(name = "frame")
    val frame: kotlin.String,

    @Json(name = "mid")
    val mid: kotlin.String,

    @Json(name = "minimap")
    val minimap: kotlin.String,

    @Json(name = "plain")
    val plain: kotlin.String

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

