/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package deadlock_api_client.models

import deadlock_api_client.models.PlayerCardSlot

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param accountId 
 * @param slots 
 * @param rankedBadgeLevel See more: <https://api.deadlock-api.com/v1/assets/ranks>
 * @param rankedRank See more: <https://api.deadlock-api.com/v1/assets/ranks>
 * @param rankedSubrank See more: <https://api.deadlock-api.com/v1/assets/ranks>
 */


data class PlayerCard (

    @Json(name = "account_id")
    val accountId: kotlin.Int,

    @Json(name = "slots")
    val slots: kotlin.collections.List<PlayerCardSlot>,

    /* See more: <https://api.deadlock-api.com/v1/assets/ranks> */
    @Json(name = "ranked_badge_level")
    val rankedBadgeLevel: kotlin.Int? = null,

    /* See more: <https://api.deadlock-api.com/v1/assets/ranks> */
    @Json(name = "ranked_rank")
    val rankedRank: kotlin.Int? = null,

    /* See more: <https://api.deadlock-api.com/v1/assets/ranks> */
    @Json(name = "ranked_subrank")
    val rankedSubrank: kotlin.Int? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

