/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package deadlock_api_client.models

import deadlock_api_client.models.ItemProperty
import deadlock_api_client.models.ItemType
import deadlock_api_client.models.RawCustomCrosshairSettings
import deadlock_api_client.models.WeaponInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param className 
 * @param id 
 * @param name 
 * @param type 
 * @param crosshairCssClass 
 * @param customCrosshairSettings 
 * @param hero 
 * @param heroes 
 * @param image 
 * @param imageWebp 
 * @param properties 
 * @param startTrained 
 * @param updateTime 
 * @param useCustomCrosshairSettings 
 * @param weaponInfo 
 */


data class Weapon (

    @Json(name = "class_name")
    val className: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "type")
    val type: ItemType,

    @Json(name = "crosshair_css_class")
    val crosshairCssClass: kotlin.String? = null,

    @Json(name = "custom_crosshair_settings")
    val customCrosshairSettings: RawCustomCrosshairSettings? = null,

    @Json(name = "hero")
    val hero: kotlin.Int? = null,

    @Json(name = "heroes")
    val heroes: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "image_webp")
    val imageWebp: kotlin.String? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, ItemProperty>? = null,

    @Json(name = "start_trained")
    val startTrained: kotlin.Boolean? = null,

    @Json(name = "update_time")
    val updateTime: kotlin.Long? = null,

    @Json(name = "use_custom_crosshair_settings")
    val useCustomCrosshairSettings: kotlin.Boolean? = null,

    @Json(name = "weapon_info")
    val weaponInfo: WeaponInfo? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

