/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package deadlock_api_client.models

import deadlock_api_client.models.RawItemWeaponInfoBulletSpeedCurve
import deadlock_api_client.models.RawWeaponInfoHorizontalRecoil
import deadlock_api_client.models.RawWeaponInfoVerticalRecoil

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param aimingShotSpreadPenalty 
 * @param buildUpRate 
 * @param bulletDamage 
 * @param bulletGravityScale 
 * @param bulletInheritShooterVelocityScale 
 * @param bulletLifetime 
 * @param bulletRadius 
 * @param bulletRadiusVsWorld 
 * @param bulletReflectAmount 
 * @param bulletReflectScale 
 * @param bulletSpeed 
 * @param bulletSpeedCurve 
 * @param bulletWhizDistance 
 * @param bullets 
 * @param bulletsPerSecond 
 * @param bulletsPerSecondWithReload 
 * @param burstShotCooldown 
 * @param burstShotCount 
 * @param canZoom 
 * @param clipSize 
 * @param critBonusAgainstNpcs 
 * @param critBonusEnd 
 * @param critBonusEndRange 
 * @param critBonusStart 
 * @param critBonusStartRange 
 * @param cycleTime 
 * @param damageFalloffBias 
 * @param damageFalloffEndRange 
 * @param damageFalloffEndScale 
 * @param damageFalloffStartRange 
 * @param damageFalloffStartScale 
 * @param damagePerMagazine 
 * @param damagePerSecond 
 * @param damagePerSecondWithReload 
 * @param damagePerShot 
 * @param horizontalPunch 
 * @param horizontalRecoil 
 * @param intraBurstCycleTime 
 * @param isSemiAuto 
 * @param lowAmmoIndicatorThreshold 
 * @param maxSpinCycleTime 
 * @param range 
 * @param recoilRecoveryDelayFactor 
 * @param recoilRecoverySpeed 
 * @param recoilSeed 
 * @param recoilShotIndexRecoveryTimeFactor 
 * @param recoilSpeed 
 * @param reloadDuration 
 * @param reloadMoveSpeed 
 * @param reloadSingleBullets 
 * @param reloadSingleBulletsAllowCancel 
 * @param reloadSingleBulletsInitialDelay 
 * @param scatterYawScale 
 * @param semiAutoCycleRate 
 * @param shootMoveSpeedPercent 
 * @param shootSpreadPenaltyDecay 
 * @param shootSpreadPenaltyDecayDelay 
 * @param shootSpreadPenaltyPerShot 
 * @param shootingUpSpreadPenalty 
 * @param shotsPerSecond 
 * @param shotsPerSecondWithReload 
 * @param spinDecayRate 
 * @param spinIncreaseRate 
 * @param spinsUp 
 * @param spread 
 * @param standingShotSpreadPenalty 
 * @param standingSpread 
 * @param verticalPunch 
 * @param verticalRecoil 
 * @param zoomFov 
 * @param zoomMoveSpeedPercent 
 */


data class WeaponInfo (

    @Json(name = "aiming_shot_spread_penalty")
    val aimingShotSpreadPenalty: kotlin.Any? = null,

    @Json(name = "build_up_rate")
    val buildUpRate: kotlin.Double? = null,

    @Json(name = "bullet_damage")
    val bulletDamage: kotlin.Double? = null,

    @Json(name = "bullet_gravity_scale")
    val bulletGravityScale: kotlin.Double? = null,

    @Json(name = "bullet_inherit_shooter_velocity_scale")
    val bulletInheritShooterVelocityScale: kotlin.Double? = null,

    @Json(name = "bullet_lifetime")
    val bulletLifetime: kotlin.Double? = null,

    @Json(name = "bullet_radius")
    val bulletRadius: kotlin.Double? = null,

    @Json(name = "bullet_radius_vs_world")
    val bulletRadiusVsWorld: kotlin.Double? = null,

    @Json(name = "bullet_reflect_amount")
    val bulletReflectAmount: kotlin.Double? = null,

    @Json(name = "bullet_reflect_scale")
    val bulletReflectScale: kotlin.Double? = null,

    @Json(name = "bullet_speed")
    val bulletSpeed: kotlin.Double? = null,

    @Json(name = "bullet_speed_curve")
    val bulletSpeedCurve: RawItemWeaponInfoBulletSpeedCurve? = null,

    @Json(name = "bullet_whiz_distance")
    val bulletWhizDistance: kotlin.Double? = null,

    @Json(name = "bullets")
    val bullets: kotlin.Int? = null,

    @Json(name = "bullets_per_second")
    val bulletsPerSecond: kotlin.Double? = null,

    @Json(name = "bullets_per_second_with_reload")
    val bulletsPerSecondWithReload: kotlin.Double? = null,

    @Json(name = "burst_shot_cooldown")
    val burstShotCooldown: kotlin.Double? = null,

    @Json(name = "burst_shot_count")
    val burstShotCount: kotlin.Int? = null,

    @Json(name = "can_zoom")
    val canZoom: kotlin.Boolean? = null,

    @Json(name = "clip_size")
    val clipSize: kotlin.Int? = null,

    @Json(name = "crit_bonus_against_npcs")
    val critBonusAgainstNpcs: kotlin.Double? = null,

    @Json(name = "crit_bonus_end")
    val critBonusEnd: kotlin.Double? = null,

    @Json(name = "crit_bonus_end_range")
    val critBonusEndRange: kotlin.Double? = null,

    @Json(name = "crit_bonus_start")
    val critBonusStart: kotlin.Double? = null,

    @Json(name = "crit_bonus_start_range")
    val critBonusStartRange: kotlin.Double? = null,

    @Json(name = "cycle_time")
    val cycleTime: kotlin.Double? = null,

    @Json(name = "damage_falloff_bias")
    val damageFalloffBias: kotlin.Double? = null,

    @Json(name = "damage_falloff_end_range")
    val damageFalloffEndRange: kotlin.Double? = null,

    @Json(name = "damage_falloff_end_scale")
    val damageFalloffEndScale: kotlin.Double? = null,

    @Json(name = "damage_falloff_start_range")
    val damageFalloffStartRange: kotlin.Double? = null,

    @Json(name = "damage_falloff_start_scale")
    val damageFalloffStartScale: kotlin.Double? = null,

    @Json(name = "damage_per_magazine")
    val damagePerMagazine: kotlin.Double? = null,

    @Json(name = "damage_per_second")
    val damagePerSecond: kotlin.Double? = null,

    @Json(name = "damage_per_second_with_reload")
    val damagePerSecondWithReload: kotlin.Double? = null,

    @Json(name = "damage_per_shot")
    val damagePerShot: kotlin.Double? = null,

    @Json(name = "horizontal_punch")
    val horizontalPunch: kotlin.Double? = null,

    @Json(name = "horizontal_recoil")
    val horizontalRecoil: RawWeaponInfoHorizontalRecoil? = null,

    @Json(name = "intra_burst_cycle_time")
    val intraBurstCycleTime: kotlin.Double? = null,

    @Json(name = "is_semi_auto")
    val isSemiAuto: kotlin.Boolean? = null,

    @Json(name = "low_ammo_indicator_threshold")
    val lowAmmoIndicatorThreshold: kotlin.Double? = null,

    @Json(name = "max_spin_cycle_time")
    val maxSpinCycleTime: kotlin.Double? = null,

    @Json(name = "range")
    val range: kotlin.Double? = null,

    @Json(name = "recoil_recovery_delay_factor")
    val recoilRecoveryDelayFactor: kotlin.Double? = null,

    @Json(name = "recoil_recovery_speed")
    val recoilRecoverySpeed: kotlin.Double? = null,

    @Json(name = "recoil_seed")
    val recoilSeed: kotlin.Double? = null,

    @Json(name = "recoil_shot_index_recovery_time_factor")
    val recoilShotIndexRecoveryTimeFactor: kotlin.Double? = null,

    @Json(name = "recoil_speed")
    val recoilSpeed: kotlin.Double? = null,

    @Json(name = "reload_duration")
    val reloadDuration: kotlin.Double? = null,

    @Json(name = "reload_move_speed")
    val reloadMoveSpeed: kotlin.Double? = null,

    @Json(name = "reload_single_bullets")
    val reloadSingleBullets: kotlin.Boolean? = null,

    @Json(name = "reload_single_bullets_allow_cancel")
    val reloadSingleBulletsAllowCancel: kotlin.Boolean? = null,

    @Json(name = "reload_single_bullets_initial_delay")
    val reloadSingleBulletsInitialDelay: kotlin.Double? = null,

    @Json(name = "scatter_yaw_scale")
    val scatterYawScale: kotlin.Double? = null,

    @Json(name = "semi_auto_cycle_rate")
    val semiAutoCycleRate: kotlin.Double? = null,

    @Json(name = "shoot_move_speed_percent")
    val shootMoveSpeedPercent: kotlin.Double? = null,

    @Json(name = "shoot_spread_penalty_decay")
    val shootSpreadPenaltyDecay: kotlin.Double? = null,

    @Json(name = "shoot_spread_penalty_decay_delay")
    val shootSpreadPenaltyDecayDelay: kotlin.Double? = null,

    @Json(name = "shoot_spread_penalty_per_shot")
    val shootSpreadPenaltyPerShot: kotlin.Double? = null,

    @Json(name = "shooting_up_spread_penalty")
    val shootingUpSpreadPenalty: kotlin.Double? = null,

    @Json(name = "shots_per_second")
    val shotsPerSecond: kotlin.Double? = null,

    @Json(name = "shots_per_second_with_reload")
    val shotsPerSecondWithReload: kotlin.Double? = null,

    @Json(name = "spin_decay_rate")
    val spinDecayRate: kotlin.Double? = null,

    @Json(name = "spin_increase_rate")
    val spinIncreaseRate: kotlin.Double? = null,

    @Json(name = "spins_up")
    val spinsUp: kotlin.Boolean? = null,

    @Json(name = "spread")
    val spread: kotlin.Double? = null,

    @Json(name = "standing_shot_spread_penalty")
    val standingShotSpreadPenalty: kotlin.Any? = null,

    @Json(name = "standing_spread")
    val standingSpread: kotlin.Double? = null,

    @Json(name = "vertical_punch")
    val verticalPunch: kotlin.Double? = null,

    @Json(name = "vertical_recoil")
    val verticalRecoil: RawWeaponInfoVerticalRecoil? = null,

    @Json(name = "zoom_fov")
    val zoomFov: kotlin.Double? = null,

    @Json(name = "zoom_move_speed_percent")
    val zoomMoveSpeedPercent: kotlin.Double? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

