/*
 * Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericData {
    #[serde(rename = "aim_spring_strength")]
    pub aim_spring_strength: Vec<f64>,
    #[serde(rename = "armor_groups")]
    pub armor_groups: Vec<models::ItemGroup>,
    #[serde(rename = "damage_flash")]
    pub damage_flash: Box<models::DamageFlash>,
    #[serde(rename = "enemy_objectives_and_zipline_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enemy_objectives_and_zipline_color: Option<Option<Box<models::Color>>>,
    #[serde(rename = "enemy_objectives_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enemy_objectives_color: Option<Option<Box<models::Color>>>,
    #[serde(rename = "enemy_zipline_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enemy_zipline_color: Option<Option<Box<models::Color>>>,
    #[serde(rename = "glitch_settings")]
    pub glitch_settings: Box<models::GlitchSettings>,
    #[serde(rename = "hero_kill_gold_share_frac")]
    pub hero_kill_gold_share_frac: Vec<f64>,
    #[serde(rename = "item_price_per_tier")]
    pub item_price_per_tier: Vec<i64>,
    #[serde(rename = "lane_info")]
    pub lane_info: Vec<models::LaneInfo>,
    #[serde(rename = "mini_map_offsets")]
    pub mini_map_offsets: Vec<models::MiniMapOffsets>,
    #[serde(rename = "minimap_team_combine_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimap_team_combine_color: Option<Option<Box<models::Color>>>,
    #[serde(rename = "minimap_team_rebels_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimap_team_rebels_color: Option<Option<Box<models::Color>>>,
    #[serde(rename = "new_player_metrics")]
    pub new_player_metrics: Vec<models::NewPlayerMetrics>,
    #[serde(rename = "objective_params")]
    pub objective_params: Box<models::ObjectiveParams>,
    #[serde(rename = "rejuv_params")]
    pub rejuv_params: Box<models::RejuvParams>,
    #[serde(rename = "spirit_groups")]
    pub spirit_groups: Vec<models::ItemGroup>,
    #[serde(rename = "street_brawl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub street_brawl: Option<Option<Box<models::StreetBrawl>>>,
    #[serde(rename = "targeting_spring_strength")]
    pub targeting_spring_strength: Vec<f64>,
    #[serde(rename = "trooper_kill_gold_share_frac")]
    pub trooper_kill_gold_share_frac: Vec<f64>,
    #[serde(rename = "weapon_groups")]
    pub weapon_groups: Vec<models::ItemGroup>,
}

impl GenericData {
    pub fn new(aim_spring_strength: Vec<f64>, armor_groups: Vec<models::ItemGroup>, damage_flash: models::DamageFlash, glitch_settings: models::GlitchSettings, hero_kill_gold_share_frac: Vec<f64>, item_price_per_tier: Vec<i64>, lane_info: Vec<models::LaneInfo>, mini_map_offsets: Vec<models::MiniMapOffsets>, new_player_metrics: Vec<models::NewPlayerMetrics>, objective_params: models::ObjectiveParams, rejuv_params: models::RejuvParams, spirit_groups: Vec<models::ItemGroup>, targeting_spring_strength: Vec<f64>, trooper_kill_gold_share_frac: Vec<f64>, weapon_groups: Vec<models::ItemGroup>) -> GenericData {
        GenericData {
            aim_spring_strength,
            armor_groups,
            damage_flash: Box::new(damage_flash),
            enemy_objectives_and_zipline_color: None,
            enemy_objectives_color: None,
            enemy_zipline_color: None,
            glitch_settings: Box::new(glitch_settings),
            hero_kill_gold_share_frac,
            item_price_per_tier,
            lane_info,
            mini_map_offsets,
            minimap_team_combine_color: None,
            minimap_team_rebels_color: None,
            new_player_metrics,
            objective_params: Box::new(objective_params),
            rejuv_params: Box::new(rejuv_params),
            spirit_groups,
            street_brawl: None,
            targeting_spring_strength,
            trooper_kill_gold_share_frac,
            weapon_groups,
        }
    }
}

