// tslint:disable
/**
 * Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CorruptedTooltipBackers,
    CorruptedTooltipBackersFromJSON,
    CorruptedTooltipBackersToJSON,
    ImagePair,
    ImagePairFromJSON,
    ImagePairToJSON,
} from './';

/**
 * Shop art for corrupted items (build 6711+). The game has no per-item corrupted icon: a corrupted item is its normal image drawn inside `frame`, with the tooltip backer of its `item_slot_type`.
 * @export
 * @interface CorruptedItemImages
 */
export interface CorruptedItemImages  {
    /**
     * 
     * @type {ImagePair}
     * @memberof CorruptedItemImages
     */
    frame: ImagePair;
    /**
     * Frame for an active (usable) corrupted item.
     * @type {ImagePair}
     * @memberof CorruptedItemImages
     */
    frameActive: ImagePair;
    /**
     * 
     * @type {CorruptedTooltipBackers}
     * @memberof CorruptedItemImages
     */
    tooltipBackers: CorruptedTooltipBackers;
}

export function CorruptedItemImagesFromJSON(json: any): CorruptedItemImages {
    return {
        'frame': ImagePairFromJSON(json['frame']),
        'frameActive': ImagePairFromJSON(json['frame_active']),
        'tooltipBackers': CorruptedTooltipBackersFromJSON(json['tooltip_backers']),
    };
}

export function CorruptedItemImagesToJSON(value?: CorruptedItemImages): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'frame': ImagePairToJSON(value.frame),
        'frame_active': ImagePairToJSON(value.frameActive),
        'tooltip_backers': CorruptedTooltipBackersToJSON(value.tooltipBackers),
    };
}


