// tslint:disable
/**
 * Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Modifier
 */
export interface Modifier  {
    /**
     * Entry this one inherits from (`_base`).
     * @type {string}
     * @memberof Modifier
     */
    base?: string;
    /**
     * Engine class (`_class`), e.g. `citadel_neutral_laser_beam`.
     * @type {string}
     * @memberof Modifier
     */
    _class?: string;
    /**
     * 
     * @type {string}
     * @memberof Modifier
     */
    className: string;
    /**
     * Editor folder (`_editor.folder_name`), e.g. `Neutral Ability`.
     * @type {string}
     * @memberof Modifier
     */
    folder?: string;
    /**
     * 
     * @type {number}
     * @memberof Modifier
     */
    id: number;
    /**
     * Numeric properties keyed by their source name. Nested properties use a dotted path (`m_GroundAuraModifier.m_modifierProvidedByAura.m_flDPS`, `subclass:` wrappers are skipped); `m_vecScriptValues` entries are keyed by their `m_eModifierValue` (`MODIFIER_VALUE_GRAVITY_SCALE`).
     * @type {{ [key: string]: number; }}
     * @memberof Modifier
     */
    properties: { [key: string]: number; };
}

export function ModifierFromJSON(json: any): Modifier {
    return {
        'base': !exists(json, 'base') ? undefined : json['base'],
        '_class': !exists(json, 'class') ? undefined : json['class'],
        'className': json['class_name'],
        'folder': !exists(json, 'folder') ? undefined : json['folder'],
        'id': json['id'],
        'properties': json['properties'],
    };
}

export function ModifierToJSON(value?: Modifier): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'base': value.base,
        'class': value._class,
        'class_name': value.className,
        'folder': value.folder,
        'id': value.id,
        'properties': value.properties,
    };
}


