// tslint:disable
/**
 * Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Crosshair convars. Anything not given keeps the game\'s default.
 * @export
 * @interface Settings
 */
export interface Settings  {
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    colorB?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    colorG?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    colorR?: number;
    /**
     * 0 to 1.
     * @type {number}
     * @memberof Settings
     */
    dotOpacity?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    dotOutlineBorder?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    dotOutlineGap?: number;
    /**
     * 0 to 1.
     * @type {number}
     * @memberof Settings
     */
    dotOutlineOpacity?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    dotSize?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    outlineColorB?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    outlineColorG?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    outlineColorR?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    pipGap?: number;
    /**
     * Keep the pips at a fixed distance instead of spreading them with weapon spread.
     * @type {boolean}
     * @memberof Settings
     */
    pipGapStatic?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    pipHeight?: number;
    /**
     * 0 to 1.
     * @type {number}
     * @memberof Settings
     */
    pipOpacity?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    pipOutlineBorder?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    pipOutlineGap?: number;
    /**
     * 0 to 1.
     * @type {number}
     * @memberof Settings
     */
    pipOutlineOpacity?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    pipWidth?: number;
    /**
     * Use the hero\'s own crosshair instead of these settings.
     * @type {boolean}
     * @memberof Settings
     */
    themed?: boolean;
}

export function SettingsFromJSON(json: any): Settings {
    return {
        'colorB': !exists(json, 'color_b') ? undefined : json['color_b'],
        'colorG': !exists(json, 'color_g') ? undefined : json['color_g'],
        'colorR': !exists(json, 'color_r') ? undefined : json['color_r'],
        'dotOpacity': !exists(json, 'dot_opacity') ? undefined : json['dot_opacity'],
        'dotOutlineBorder': !exists(json, 'dot_outline_border') ? undefined : json['dot_outline_border'],
        'dotOutlineGap': !exists(json, 'dot_outline_gap') ? undefined : json['dot_outline_gap'],
        'dotOutlineOpacity': !exists(json, 'dot_outline_opacity') ? undefined : json['dot_outline_opacity'],
        'dotSize': !exists(json, 'dot_size') ? undefined : json['dot_size'],
        'outlineColorB': !exists(json, 'outline_color_b') ? undefined : json['outline_color_b'],
        'outlineColorG': !exists(json, 'outline_color_g') ? undefined : json['outline_color_g'],
        'outlineColorR': !exists(json, 'outline_color_r') ? undefined : json['outline_color_r'],
        'pipGap': !exists(json, 'pip_gap') ? undefined : json['pip_gap'],
        'pipGapStatic': !exists(json, 'pip_gap_static') ? undefined : json['pip_gap_static'],
        'pipHeight': !exists(json, 'pip_height') ? undefined : json['pip_height'],
        'pipOpacity': !exists(json, 'pip_opacity') ? undefined : json['pip_opacity'],
        'pipOutlineBorder': !exists(json, 'pip_outline_border') ? undefined : json['pip_outline_border'],
        'pipOutlineGap': !exists(json, 'pip_outline_gap') ? undefined : json['pip_outline_gap'],
        'pipOutlineOpacity': !exists(json, 'pip_outline_opacity') ? undefined : json['pip_outline_opacity'],
        'pipWidth': !exists(json, 'pip_width') ? undefined : json['pip_width'],
        'themed': !exists(json, 'themed') ? undefined : json['themed'],
    };
}

export function SettingsToJSON(value?: Settings): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'color_b': value.colorB,
        'color_g': value.colorG,
        'color_r': value.colorR,
        'dot_opacity': value.dotOpacity,
        'dot_outline_border': value.dotOutlineBorder,
        'dot_outline_gap': value.dotOutlineGap,
        'dot_outline_opacity': value.dotOutlineOpacity,
        'dot_size': value.dotSize,
        'outline_color_b': value.outlineColorB,
        'outline_color_g': value.outlineColorG,
        'outline_color_r': value.outlineColorR,
        'pip_gap': value.pipGap,
        'pip_gap_static': value.pipGapStatic,
        'pip_height': value.pipHeight,
        'pip_opacity': value.pipOpacity,
        'pip_outline_border': value.pipOutlineBorder,
        'pip_outline_gap': value.pipOutlineGap,
        'pip_outline_opacity': value.pipOutlineOpacity,
        'pip_width': value.pipWidth,
        'themed': value.themed,
    };
}


