/*
Deadlock API

 ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package deadlock_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LootEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LootEntry{}

// LootEntry struct for LootEntry
type LootEntry struct {
	Item string `json:"item"`
}

type _LootEntry LootEntry

// NewLootEntry instantiates a new LootEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLootEntry(item string) *LootEntry {
	this := LootEntry{}
	this.Item = item
	return &this
}

// NewLootEntryWithDefaults instantiates a new LootEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLootEntryWithDefaults() *LootEntry {
	this := LootEntry{}
	return &this
}

// GetItem returns the Item field value
func (o *LootEntry) GetItem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *LootEntry) GetItemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *LootEntry) SetItem(v string) {
	o.Item = v
}

func (o LootEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LootEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["item"] = o.Item
	return toSerialize, nil
}

func (o *LootEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"item",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLootEntry := _LootEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLootEntry)

	if err != nil {
		return err
	}

	*o = LootEntry(varLootEntry)

	return err
}

type NullableLootEntry struct {
	value *LootEntry
	isSet bool
}

func (v NullableLootEntry) Get() *LootEntry {
	return v.value
}

func (v *NullableLootEntry) Set(val *LootEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableLootEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableLootEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLootEntry(val *LootEntry) *NullableLootEntry {
	return &NullableLootEntry{value: val, isSet: true}
}

func (v NullableLootEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLootEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


