/*
Deadlock API

 ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package deadlock_api_client

import (
	"encoding/json"
	"fmt"
)

// AbilityType the model 'AbilityType'
type AbilityType string

// List of AbilityType
const (
	ABILITYTYPE_INNATE AbilityType = "innate"
	ABILITYTYPE_ITEM AbilityType = "item"
	ABILITYTYPE_SIGNATURE AbilityType = "signature"
	ABILITYTYPE_ULTIMATE AbilityType = "ultimate"
	ABILITYTYPE_WEAPON AbilityType = "weapon"
	ABILITYTYPE_MELEE AbilityType = "melee"
	ABILITYTYPE_COSMETIC AbilityType = "cosmetic"
)

// All allowed values of AbilityType enum
var AllowedAbilityTypeEnumValues = []AbilityType{
	"innate",
	"item",
	"signature",
	"ultimate",
	"weapon",
	"melee",
	"cosmetic",
}

func (v *AbilityType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AbilityType(value)
	for _, existing := range AllowedAbilityTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AbilityType", value)
}

// NewAbilityTypeFromValue returns a pointer to a valid AbilityType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAbilityTypeFromValue(v string) (*AbilityType, error) {
	ev := AbilityType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AbilityType: valid values are %v", v, AllowedAbilityTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AbilityType) IsValid() bool {
	for _, existing := range AllowedAbilityTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AbilityType value
func (v AbilityType) Ptr() *AbilityType {
	return &v
}

type NullableAbilityType struct {
	value *AbilityType
	isSet bool
}

func (v NullableAbilityType) Get() *AbilityType {
	return v.value
}

func (v *NullableAbilityType) Set(val *AbilityType) {
	v.value = val
	v.isSet = true
}

func (v NullableAbilityType) IsSet() bool {
	return v.isSet
}

func (v *NullableAbilityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAbilityType(val *AbilityType) *NullableAbilityType {
	return &NullableAbilityType{value: val, isSet: true}
}

func (v NullableAbilityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAbilityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

