/*
Deadlock API

 ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package deadlock_api_client

import (
	"encoding/json"
	"fmt"
)

// AbilitySectionType the model 'AbilitySectionType'
type AbilitySectionType string

// List of AbilitySectionType
const (
	ABILITYSECTIONTYPE_INNATE AbilitySectionType = "innate"
	ABILITYSECTIONTYPE_ACTIVE AbilitySectionType = "active"
	ABILITYSECTIONTYPE_PASSIVE AbilitySectionType = "passive"
)

// All allowed values of AbilitySectionType enum
var AllowedAbilitySectionTypeEnumValues = []AbilitySectionType{
	"innate",
	"active",
	"passive",
}

func (v *AbilitySectionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AbilitySectionType(value)
	for _, existing := range AllowedAbilitySectionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AbilitySectionType", value)
}

// NewAbilitySectionTypeFromValue returns a pointer to a valid AbilitySectionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAbilitySectionTypeFromValue(v string) (*AbilitySectionType, error) {
	ev := AbilitySectionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AbilitySectionType: valid values are %v", v, AllowedAbilitySectionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AbilitySectionType) IsValid() bool {
	for _, existing := range AllowedAbilitySectionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AbilitySectionType value
func (v AbilitySectionType) Ptr() *AbilitySectionType {
	return &v
}

type NullableAbilitySectionType struct {
	value *AbilitySectionType
	isSet bool
}

func (v NullableAbilitySectionType) Get() *AbilitySectionType {
	return v.value
}

func (v *NullableAbilitySectionType) Set(val *AbilitySectionType) {
	v.value = val
	v.isSet = true
}

func (v NullableAbilitySectionType) IsSet() bool {
	return v.isSet
}

func (v *NullableAbilitySectionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAbilitySectionType(val *AbilitySectionType) *NullableAbilitySectionType {
	return &NullableAbilitySectionType{value: val, isSet: true}
}

func (v NullableAbilitySectionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAbilitySectionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

