/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package deadlock_api_client.models

import deadlock_api_client.models.ActiveMatchTeam

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param abandoned 
 * @param accountId 
 * @param heroId See more: <https://assets.deadlock-api.com/v2/heroes>
 * @param team 
 * @param teamParsed 
 */
@JsonClass(generateAdapter = true)

data class ActiveMatchPlayer (

    @Json(name = "abandoned")
    val abandoned: kotlin.Boolean? = null,

    @Json(name = "account_id")
    val accountId: kotlin.Int? = null,

    /* See more: <https://assets.deadlock-api.com/v2/heroes> */
    @Json(name = "hero_id")
    val heroId: kotlin.Int? = null,

    @Json(name = "team")
    val team: kotlin.Int? = null,

    @Json(name = "team_parsed")
    val teamParsed: ActiveMatchTeam? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

