/* tslint:disable */
/* eslint-disable */
/**
 * Assets - Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration.js';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common.js';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base.js';
// @ts-ignore
import type { DeadlockAssetsApiRoutesValidClientVersions } from '../models/index.js';
// @ts-ignore
import type { HTTPValidationError } from '../models/index.js';
// @ts-ignore
import type { ItemSlotTypeV2 } from '../models/index.js';
// @ts-ignore
import type { ItemTypeV2 } from '../models/index.js';
// @ts-ignore
import type { Language } from '../models/index.js';
// @ts-ignore
import type { ResponseGetItemV2ItemsIdOrClassNameGet } from '../models/index.js';
// @ts-ignore
import type { ResponseGetItemsV2ItemsGetInner } from '../models/index.js';
/**
 * ItemsApi - axios parameter creator
 */
export const ItemsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Item
         * @param {string} idOrClassName 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemV2ItemsIdOrClassNameGet: async (idOrClassName: string, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idOrClassName' is not null or undefined
            assertParamExists('getItemV2ItemsIdOrClassNameGet', 'idOrClassName', idOrClassName)
            const localVarPath = `/v2/items/{id_or_class_name}`
                .replace('{id_or_class_name}', encodeURIComponent(String(idOrClassName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (clientVersion !== undefined) {
                localVarQueryParameter['client_version'] = clientVersion;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Items By Hero Id
         * @param {number} id 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsByHeroIdV2ItemsByHeroIdIdGet: async (id: number, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getItemsByHeroIdV2ItemsByHeroIdIdGet', 'id', id)
            const localVarPath = `/v2/items/by-hero-id/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (clientVersion !== undefined) {
                localVarQueryParameter['client_version'] = clientVersion;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Items By Slot Type
         * @param {ItemSlotTypeV2} slotType 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet: async (slotType: ItemSlotTypeV2, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slotType' is not null or undefined
            assertParamExists('getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet', 'slotType', slotType)
            const localVarPath = `/v2/items/by-slot-type/{slot_type}`
                .replace('{slot_type}', encodeURIComponent(String(slotType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (clientVersion !== undefined) {
                localVarQueryParameter['client_version'] = clientVersion;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Items By Type
         * @param {ItemTypeV2} type 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsByTypeV2ItemsByTypeTypeGet: async (type: ItemTypeV2, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('getItemsByTypeV2ItemsByTypeTypeGet', 'type', type)
            const localVarPath = `/v2/items/by-type/{type}`
                .replace('{type}', encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (clientVersion !== undefined) {
                localVarQueryParameter['client_version'] = clientVersion;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Items
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsV2ItemsGet: async (language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (clientVersion !== undefined) {
                localVarQueryParameter['client_version'] = clientVersion;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ItemsApi - functional programming interface
 */
export const ItemsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ItemsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Item
         * @param {string} idOrClassName 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getItemV2ItemsIdOrClassNameGet(idOrClassName: string, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseGetItemV2ItemsIdOrClassNameGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getItemV2ItemsIdOrClassNameGet(idOrClassName, language, clientVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.getItemV2ItemsIdOrClassNameGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Items By Hero Id
         * @param {number} id 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getItemsByHeroIdV2ItemsByHeroIdIdGet(id: number, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getItemsByHeroIdV2ItemsByHeroIdIdGet(id, language, clientVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.getItemsByHeroIdV2ItemsByHeroIdIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Items By Slot Type
         * @param {ItemSlotTypeV2} slotType 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet(slotType: ItemSlotTypeV2, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet(slotType, language, clientVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Items By Type
         * @param {ItemTypeV2} type 
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getItemsByTypeV2ItemsByTypeTypeGet(type: ItemTypeV2, language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getItemsByTypeV2ItemsByTypeTypeGet(type, language, clientVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.getItemsByTypeV2ItemsByTypeTypeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Items
         * @param {Language | null} [language] 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getItemsV2ItemsGet(language?: Language | null, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getItemsV2ItemsGet(language, clientVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.getItemsV2ItemsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ItemsApi - factory interface
 */
export const ItemsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ItemsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Item
         * @param {ItemsApiGetItemV2ItemsIdOrClassNameGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemV2ItemsIdOrClassNameGet(requestParameters: ItemsApiGetItemV2ItemsIdOrClassNameGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseGetItemV2ItemsIdOrClassNameGet> {
            return localVarFp.getItemV2ItemsIdOrClassNameGet(requestParameters.idOrClassName, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Items By Hero Id
         * @param {ItemsApiGetItemsByHeroIdV2ItemsByHeroIdIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsByHeroIdV2ItemsByHeroIdIdGet(requestParameters: ItemsApiGetItemsByHeroIdV2ItemsByHeroIdIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>> {
            return localVarFp.getItemsByHeroIdV2ItemsByHeroIdIdGet(requestParameters.id, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Items By Slot Type
         * @param {ItemsApiGetItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet(requestParameters: ItemsApiGetItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>> {
            return localVarFp.getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet(requestParameters.slotType, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Items By Type
         * @param {ItemsApiGetItemsByTypeV2ItemsByTypeTypeGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsByTypeV2ItemsByTypeTypeGet(requestParameters: ItemsApiGetItemsByTypeV2ItemsByTypeTypeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>> {
            return localVarFp.getItemsByTypeV2ItemsByTypeTypeGet(requestParameters.type, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Items
         * @param {ItemsApiGetItemsV2ItemsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsV2ItemsGet(requestParameters: ItemsApiGetItemsV2ItemsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<ResponseGetItemsV2ItemsGetInner>> {
            return localVarFp.getItemsV2ItemsGet(requestParameters.language, requestParameters.clientVersion, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getItemV2ItemsIdOrClassNameGet operation in ItemsApi.
 */
export interface ItemsApiGetItemV2ItemsIdOrClassNameGetRequest {
    readonly idOrClassName: string

    readonly language?: Language | null

    readonly clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null
}

/**
 * Request parameters for getItemsByHeroIdV2ItemsByHeroIdIdGet operation in ItemsApi.
 */
export interface ItemsApiGetItemsByHeroIdV2ItemsByHeroIdIdGetRequest {
    readonly id: number

    readonly language?: Language | null

    readonly clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null
}

/**
 * Request parameters for getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet operation in ItemsApi.
 */
export interface ItemsApiGetItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGetRequest {
    readonly slotType: ItemSlotTypeV2

    readonly language?: Language | null

    readonly clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null
}

/**
 * Request parameters for getItemsByTypeV2ItemsByTypeTypeGet operation in ItemsApi.
 */
export interface ItemsApiGetItemsByTypeV2ItemsByTypeTypeGetRequest {
    readonly type: ItemTypeV2

    readonly language?: Language | null

    readonly clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null
}

/**
 * Request parameters for getItemsV2ItemsGet operation in ItemsApi.
 */
export interface ItemsApiGetItemsV2ItemsGetRequest {
    readonly language?: Language | null

    readonly clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null
}

/**
 * ItemsApi - object-oriented interface
 */
export class ItemsApi extends BaseAPI {
    /**
     * 
     * @summary Get Item
     * @param {ItemsApiGetItemV2ItemsIdOrClassNameGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getItemV2ItemsIdOrClassNameGet(requestParameters: ItemsApiGetItemV2ItemsIdOrClassNameGetRequest, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).getItemV2ItemsIdOrClassNameGet(requestParameters.idOrClassName, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Items By Hero Id
     * @param {ItemsApiGetItemsByHeroIdV2ItemsByHeroIdIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getItemsByHeroIdV2ItemsByHeroIdIdGet(requestParameters: ItemsApiGetItemsByHeroIdV2ItemsByHeroIdIdGetRequest, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).getItemsByHeroIdV2ItemsByHeroIdIdGet(requestParameters.id, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Items By Slot Type
     * @param {ItemsApiGetItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet(requestParameters: ItemsApiGetItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGetRequest, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).getItemsBySlotTypeV2ItemsBySlotTypeSlotTypeGet(requestParameters.slotType, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Items By Type
     * @param {ItemsApiGetItemsByTypeV2ItemsByTypeTypeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getItemsByTypeV2ItemsByTypeTypeGet(requestParameters: ItemsApiGetItemsByTypeV2ItemsByTypeTypeGetRequest, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).getItemsByTypeV2ItemsByTypeTypeGet(requestParameters.type, requestParameters.language, requestParameters.clientVersion, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Items
     * @param {ItemsApiGetItemsV2ItemsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getItemsV2ItemsGet(requestParameters: ItemsApiGetItemsV2ItemsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).getItemsV2ItemsGet(requestParameters.language, requestParameters.clientVersion, options).then((request) => request(this.axios, this.basePath));
    }
}

