/* tslint:disable */
/* eslint-disable */
/**
 * Assets - Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_ 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration.js';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common.js';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base.js';
// @ts-ignore
import type { DeadlockAssetsApiRoutesValidClientVersions } from '../models/index.js';
// @ts-ignore
import type { HTTPValidationError } from '../models/index.js';
// @ts-ignore
import type { NPCUnitV2 } from '../models/index.js';
/**
 * NPCUnitsApi - axios parameter creator
 */
export const NPCUnitsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Npc Unit
         * @param {string} idOrClassName 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNpcUnitV2NpcUnitsIdOrClassNameGet: async (idOrClassName: string, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idOrClassName' is not null or undefined
            assertParamExists('getNpcUnitV2NpcUnitsIdOrClassNameGet', 'idOrClassName', idOrClassName)
            const localVarPath = `/v2/npc-units/{id_or_class_name}`
                .replace('{id_or_class_name}', encodeURIComponent(String(idOrClassName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clientVersion !== undefined) {
                localVarQueryParameter['client_version'] = clientVersion;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Npc Units
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNpcUnitsV2NpcUnitsGet: async (clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/npc-units`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clientVersion !== undefined) {
                localVarQueryParameter['client_version'] = clientVersion;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NPCUnitsApi - functional programming interface
 */
export const NPCUnitsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NPCUnitsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Npc Unit
         * @param {string} idOrClassName 
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNpcUnitV2NpcUnitsIdOrClassNameGet(idOrClassName: string, clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NPCUnitV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNpcUnitV2NpcUnitsIdOrClassNameGet(idOrClassName, clientVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NPCUnitsApi.getNpcUnitV2NpcUnitsIdOrClassNameGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Npc Units
         * @param {DeadlockAssetsApiRoutesValidClientVersions | null} [clientVersion] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNpcUnitsV2NpcUnitsGet(clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NPCUnitV2>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNpcUnitsV2NpcUnitsGet(clientVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NPCUnitsApi.getNpcUnitsV2NpcUnitsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NPCUnitsApi - factory interface
 */
export const NPCUnitsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NPCUnitsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Npc Unit
         * @param {NPCUnitsApiGetNpcUnitV2NpcUnitsIdOrClassNameGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNpcUnitV2NpcUnitsIdOrClassNameGet(requestParameters: NPCUnitsApiGetNpcUnitV2NpcUnitsIdOrClassNameGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<NPCUnitV2> {
            return localVarFp.getNpcUnitV2NpcUnitsIdOrClassNameGet(requestParameters.idOrClassName, requestParameters.clientVersion, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Npc Units
         * @param {NPCUnitsApiGetNpcUnitsV2NpcUnitsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNpcUnitsV2NpcUnitsGet(requestParameters: NPCUnitsApiGetNpcUnitsV2NpcUnitsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<NPCUnitV2>> {
            return localVarFp.getNpcUnitsV2NpcUnitsGet(requestParameters.clientVersion, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getNpcUnitV2NpcUnitsIdOrClassNameGet operation in NPCUnitsApi.
 */
export interface NPCUnitsApiGetNpcUnitV2NpcUnitsIdOrClassNameGetRequest {
    readonly idOrClassName: string

    readonly clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null
}

/**
 * Request parameters for getNpcUnitsV2NpcUnitsGet operation in NPCUnitsApi.
 */
export interface NPCUnitsApiGetNpcUnitsV2NpcUnitsGetRequest {
    readonly clientVersion?: DeadlockAssetsApiRoutesValidClientVersions | null
}

/**
 * NPCUnitsApi - object-oriented interface
 */
export class NPCUnitsApi extends BaseAPI {
    /**
     * 
     * @summary Get Npc Unit
     * @param {NPCUnitsApiGetNpcUnitV2NpcUnitsIdOrClassNameGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNpcUnitV2NpcUnitsIdOrClassNameGet(requestParameters: NPCUnitsApiGetNpcUnitV2NpcUnitsIdOrClassNameGetRequest, options?: RawAxiosRequestConfig) {
        return NPCUnitsApiFp(this.configuration).getNpcUnitV2NpcUnitsIdOrClassNameGet(requestParameters.idOrClassName, requestParameters.clientVersion, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Npc Units
     * @param {NPCUnitsApiGetNpcUnitsV2NpcUnitsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNpcUnitsV2NpcUnitsGet(requestParameters: NPCUnitsApiGetNpcUnitsV2NpcUnitsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return NPCUnitsApiFp(this.configuration).getNpcUnitsV2NpcUnitsGet(requestParameters.clientVersion, options).then((request) => request(this.axios, this.basePath));
    }
}

