/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package assets_deadlock_api_client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param className 
 * @param subclassName 
 * @param specificStatScaleType 
 * @param scalingStats 
 * @param statScale 
 */


data class RawItemPropertyScaleFunctionSubclassV2 (

    @Json(name = "class_name")
    val className: kotlin.String? = null,

    @Json(name = "subclass_name")
    val subclassName: kotlin.String? = null,

    @Json(name = "specific_stat_scale_type")
    val specificStatScaleType: kotlin.String? = null,

    @Json(name = "scaling_stats")
    val scalingStats: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "stat_scale")
    val statScale: java.math.BigDecimal? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

