/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package deadlock-api-client.models

import deadlock-api-client.models.BuildHeroDetailsCategoryAbility

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param description 
 * @param height 
 * @param mods 
 * @param optional 
 * @param width 
 */


data class BuildHeroDetailsCategory (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "height")
    val height: kotlin.Float? = null,

    @Json(name = "mods")
    val mods: kotlin.collections.List<BuildHeroDetailsCategoryAbility>? = null,

    @Json(name = "optional")
    val optional: kotlin.Boolean? = null,

    @Json(name = "width")
    val width: kotlin.Float? = null

) {


}

