/* tslint:disable */
/* eslint-disable */
/**
 * Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Build } from '../models';
/**
 * BuildsApi - axios parameter creator
 */
export const BuildsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *  Search for builds based on various criteria.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 100req/s | | Key | - | | Global | - |     
         * @summary Search
         * @param {number} [minUnixTimestamp] Filter builds based on their &#x60;last_updated&#x60; time (Unix timestamp).
         * @param {number} [maxUnixTimestamp] Filter builds based on their &#x60;last_updated&#x60; time (Unix timestamp).
         * @param {number} [minPublishedUnixTimestamp] Filter builds based on their published time (Unix timestamp).
         * @param {number} [maxPublishedUnixTimestamp] Filter builds based on their published time (Unix timestamp).
         * @param {SearchBuildsSortByEnum} [sortBy] The field to sort the builds by.
         * @param {number} [start] The index of the first build to return.
         * @param {number} [limit] The maximum number of builds to return.
         * @param {SearchBuildsSortDirectionEnum} [sortDirection] The direction to sort the builds in.
         * @param {string} [searchName] Search for builds with a name containing this string.
         * @param {string} [searchDescription] Search for builds with a description containing this string.
         * @param {boolean} [onlyLatest] Only return the latest version of each build.
         * @param {number} [language] Filter builds by language.
         * @param {SearchBuildsBuildLanguageEnum} [buildLanguage] Filter builds by language.
         * @param {number} [buildId] Filter builds by ID.
         * @param {number} [version] Filter builds by version.
         * @param {number} [heroId] Filter builds by hero ID. See more: &lt;https://assets.deadlock-api.com/v2/heroes&gt;
         * @param {number} [tag] Filter builds by tag.
         * @param {number} [rollupCategory] Filter builds by rollup category.
         * @param {number} [authorId] The author\&#39;s &#x60;SteamID3&#x60;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchBuilds: async (minUnixTimestamp?: number, maxUnixTimestamp?: number, minPublishedUnixTimestamp?: number, maxPublishedUnixTimestamp?: number, sortBy?: SearchBuildsSortByEnum, start?: number, limit?: number, sortDirection?: SearchBuildsSortDirectionEnum, searchName?: string, searchDescription?: string, onlyLatest?: boolean, language?: number, buildLanguage?: SearchBuildsBuildLanguageEnum, buildId?: number, version?: number, heroId?: number, tag?: number, rollupCategory?: number, authorId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/builds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (minUnixTimestamp !== undefined) {
                localVarQueryParameter['min_unix_timestamp'] = minUnixTimestamp;
            }

            if (maxUnixTimestamp !== undefined) {
                localVarQueryParameter['max_unix_timestamp'] = maxUnixTimestamp;
            }

            if (minPublishedUnixTimestamp !== undefined) {
                localVarQueryParameter['min_published_unix_timestamp'] = minPublishedUnixTimestamp;
            }

            if (maxPublishedUnixTimestamp !== undefined) {
                localVarQueryParameter['max_published_unix_timestamp'] = maxPublishedUnixTimestamp;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortDirection !== undefined) {
                localVarQueryParameter['sort_direction'] = sortDirection;
            }

            if (searchName !== undefined) {
                localVarQueryParameter['search_name'] = searchName;
            }

            if (searchDescription !== undefined) {
                localVarQueryParameter['search_description'] = searchDescription;
            }

            if (onlyLatest !== undefined) {
                localVarQueryParameter['only_latest'] = onlyLatest;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (buildLanguage !== undefined) {
                localVarQueryParameter['build_language'] = buildLanguage;
            }

            if (buildId !== undefined) {
                localVarQueryParameter['build_id'] = buildId;
            }

            if (version !== undefined) {
                localVarQueryParameter['version'] = version;
            }

            if (heroId !== undefined) {
                localVarQueryParameter['hero_id'] = heroId;
            }

            if (tag !== undefined) {
                localVarQueryParameter['tag'] = tag;
            }

            if (rollupCategory !== undefined) {
                localVarQueryParameter['rollup_category'] = rollupCategory;
            }

            if (authorId !== undefined) {
                localVarQueryParameter['author_id'] = authorId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BuildsApi - functional programming interface
 */
export const BuildsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BuildsApiAxiosParamCreator(configuration)
    return {
        /**
         *  Search for builds based on various criteria.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 100req/s | | Key | - | | Global | - |     
         * @summary Search
         * @param {number} [minUnixTimestamp] Filter builds based on their &#x60;last_updated&#x60; time (Unix timestamp).
         * @param {number} [maxUnixTimestamp] Filter builds based on their &#x60;last_updated&#x60; time (Unix timestamp).
         * @param {number} [minPublishedUnixTimestamp] Filter builds based on their published time (Unix timestamp).
         * @param {number} [maxPublishedUnixTimestamp] Filter builds based on their published time (Unix timestamp).
         * @param {SearchBuildsSortByEnum} [sortBy] The field to sort the builds by.
         * @param {number} [start] The index of the first build to return.
         * @param {number} [limit] The maximum number of builds to return.
         * @param {SearchBuildsSortDirectionEnum} [sortDirection] The direction to sort the builds in.
         * @param {string} [searchName] Search for builds with a name containing this string.
         * @param {string} [searchDescription] Search for builds with a description containing this string.
         * @param {boolean} [onlyLatest] Only return the latest version of each build.
         * @param {number} [language] Filter builds by language.
         * @param {SearchBuildsBuildLanguageEnum} [buildLanguage] Filter builds by language.
         * @param {number} [buildId] Filter builds by ID.
         * @param {number} [version] Filter builds by version.
         * @param {number} [heroId] Filter builds by hero ID. See more: &lt;https://assets.deadlock-api.com/v2/heroes&gt;
         * @param {number} [tag] Filter builds by tag.
         * @param {number} [rollupCategory] Filter builds by rollup category.
         * @param {number} [authorId] The author\&#39;s &#x60;SteamID3&#x60;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchBuilds(minUnixTimestamp?: number, maxUnixTimestamp?: number, minPublishedUnixTimestamp?: number, maxPublishedUnixTimestamp?: number, sortBy?: SearchBuildsSortByEnum, start?: number, limit?: number, sortDirection?: SearchBuildsSortDirectionEnum, searchName?: string, searchDescription?: string, onlyLatest?: boolean, language?: number, buildLanguage?: SearchBuildsBuildLanguageEnum, buildId?: number, version?: number, heroId?: number, tag?: number, rollupCategory?: number, authorId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Build>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchBuilds(minUnixTimestamp, maxUnixTimestamp, minPublishedUnixTimestamp, maxPublishedUnixTimestamp, sortBy, start, limit, sortDirection, searchName, searchDescription, onlyLatest, language, buildLanguage, buildId, version, heroId, tag, rollupCategory, authorId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BuildsApi.searchBuilds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BuildsApi - factory interface
 */
export const BuildsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BuildsApiFp(configuration)
    return {
        /**
         *  Search for builds based on various criteria.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 100req/s | | Key | - | | Global | - |     
         * @summary Search
         * @param {BuildsApiSearchBuildsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchBuilds(requestParameters: BuildsApiSearchBuildsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<Build>> {
            return localVarFp.searchBuilds(requestParameters.minUnixTimestamp, requestParameters.maxUnixTimestamp, requestParameters.minPublishedUnixTimestamp, requestParameters.maxPublishedUnixTimestamp, requestParameters.sortBy, requestParameters.start, requestParameters.limit, requestParameters.sortDirection, requestParameters.searchName, requestParameters.searchDescription, requestParameters.onlyLatest, requestParameters.language, requestParameters.buildLanguage, requestParameters.buildId, requestParameters.version, requestParameters.heroId, requestParameters.tag, requestParameters.rollupCategory, requestParameters.authorId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for searchBuilds operation in BuildsApi.
 */
export interface BuildsApiSearchBuildsRequest {
    /**
     * Filter builds based on their &#x60;last_updated&#x60; time (Unix timestamp).
     */
    readonly minUnixTimestamp?: number

    /**
     * Filter builds based on their &#x60;last_updated&#x60; time (Unix timestamp).
     */
    readonly maxUnixTimestamp?: number

    /**
     * Filter builds based on their published time (Unix timestamp).
     */
    readonly minPublishedUnixTimestamp?: number

    /**
     * Filter builds based on their published time (Unix timestamp).
     */
    readonly maxPublishedUnixTimestamp?: number

    /**
     * The field to sort the builds by.
     */
    readonly sortBy?: SearchBuildsSortByEnum

    /**
     * The index of the first build to return.
     */
    readonly start?: number

    /**
     * The maximum number of builds to return.
     */
    readonly limit?: number

    /**
     * The direction to sort the builds in.
     */
    readonly sortDirection?: SearchBuildsSortDirectionEnum

    /**
     * Search for builds with a name containing this string.
     */
    readonly searchName?: string

    /**
     * Search for builds with a description containing this string.
     */
    readonly searchDescription?: string

    /**
     * Only return the latest version of each build.
     */
    readonly onlyLatest?: boolean

    /**
     * Filter builds by language.
     */
    readonly language?: number

    /**
     * Filter builds by language.
     */
    readonly buildLanguage?: SearchBuildsBuildLanguageEnum

    /**
     * Filter builds by ID.
     */
    readonly buildId?: number

    /**
     * Filter builds by version.
     */
    readonly version?: number

    /**
     * Filter builds by hero ID. See more: &lt;https://assets.deadlock-api.com/v2/heroes&gt;
     */
    readonly heroId?: number

    /**
     * Filter builds by tag.
     */
    readonly tag?: number

    /**
     * Filter builds by rollup category.
     */
    readonly rollupCategory?: number

    /**
     * The author\&#39;s &#x60;SteamID3&#x60;
     */
    readonly authorId?: number
}

/**
 * BuildsApi - object-oriented interface
 */
export class BuildsApi extends BaseAPI {
    /**
     *  Search for builds based on various criteria.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 100req/s | | Key | - | | Global | - |     
     * @summary Search
     * @param {BuildsApiSearchBuildsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchBuilds(requestParameters: BuildsApiSearchBuildsRequest = {}, options?: RawAxiosRequestConfig) {
        return BuildsApiFp(this.configuration).searchBuilds(requestParameters.minUnixTimestamp, requestParameters.maxUnixTimestamp, requestParameters.minPublishedUnixTimestamp, requestParameters.maxPublishedUnixTimestamp, requestParameters.sortBy, requestParameters.start, requestParameters.limit, requestParameters.sortDirection, requestParameters.searchName, requestParameters.searchDescription, requestParameters.onlyLatest, requestParameters.language, requestParameters.buildLanguage, requestParameters.buildId, requestParameters.version, requestParameters.heroId, requestParameters.tag, requestParameters.rollupCategory, requestParameters.authorId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const SearchBuildsSortByEnum = {
    WeeklyFavorites: 'weekly_favorites',
    Favorites: 'favorites',
    Ignores: 'ignores',
    Reports: 'reports',
    UpdatedAt: 'updated_at',
    PublishedAt: 'published_at',
    Version: 'version',
} as const;
export type SearchBuildsSortByEnum = typeof SearchBuildsSortByEnum[keyof typeof SearchBuildsSortByEnum];
export const SearchBuildsSortDirectionEnum = {
    Desc: 'desc',
    Asc: 'asc',
} as const;
export type SearchBuildsSortDirectionEnum = typeof SearchBuildsSortDirectionEnum[keyof typeof SearchBuildsSortDirectionEnum];
export const SearchBuildsBuildLanguageEnum = {
    English: 'English',
    German: 'German',
    French: 'French',
    Italian: 'Italian',
    Korean: 'Korean',
    SpanishSpain: 'SpanishSpain',
    ChineseSimplified: 'ChineseSimplified',
    Russian: 'Russian',
    Thai: 'Thai',
    Japanese: 'Japanese',
    PortuguesePortugal: 'PortuguesePortugal',
    Polish: 'Polish',
    Czech: 'Czech',
    Turkish: 'Turkish',
    PortugueseBrazil: 'PortugueseBrazil',
    Ukrainian: 'Ukrainian',
    SpanishLatinAmerica: 'SpanishLatinAmerica',
    Vietnamese: 'Vietnamese',
} as const;
export type SearchBuildsBuildLanguageEnum = typeof SearchBuildsBuildLanguageEnum[keyof typeof SearchBuildsBuildLanguageEnum];
